% this file is autogenerated! -*- prolog -*-
% 1. tangle dsl/README.org using C-c C-v C-t
% 2. run (cat prelude.pl; ./mkProlog test1.l4) > potato.pl

:- use_module(library(yall)).

match(Elem, or,  List)   :- member(Elem, List).
match(Elem, and, List)   :- maplist(  [X]>>myeq(X,Elem), List).
match(Elem, xor, List)   :- partition([X]>>myeq(X,Elem), List, In, _Out), length(In,L), L = 1.
match(Elem, plain, List) :- match(Elem, or, List).
myeq(A,B) :- A == B.

% set up a couple of test potatoes
species(potato1, "Solanum tuberosum").
species(potato2, "Ipomoea batatas").

%% Parse Successful!

%% [Prolog version]

%% ruleDef: RuleDef1 (RNum 1) (RID (Ident "RuleOne"))
%% ruleBody: RBNoop
%% NOOP lol

%% ruleDef: RuleDefRuleNum (RNum 2)
%% ruleBody: RBDeem [ObjAttrAnd1 (OA_dots [ObjAttrElemIdent (Ident "Item"),ObjAttrElemIdent (Ident "isEdiblePotato")]),ObjAttrAnd1 (OA_dots [ObjAttrElemIdent (Ident "Item"),ObjAttrElemIdent (Ident "isTastyFood")])] (PEAnd (PEOA (OA_dots [ObjAttrElemIdent (Ident "Item"),ObjAttrElemIdent (Ident "isPotato")])) (PEOA (OA_dots [ObjAttrElemIdent (Ident "Item"),ObjAttrElemIdent (Ident "isEdible")])))
isEdiblePotato(Item) :- isPotato(Item), isEdible(Item).
isTastyFood(Item) :- isPotato(Item), isEdible(Item).


%% ruleDef: RuleDef1 (RNum 3) (RID (Ident "fertilize"))
%% ruleBody: RBDeem [ObjAttrAnd1 (OA_dots [ObjAttrElemIdent (Ident "Item"),ObjAttrElemIdent (Ident "isPotato")])] (PEME (ME_OA_JL (OA_dots [ObjAttrElemIdent (Ident "Item"),ObjAttrElemIdent (Ident "Species")]) (JL_Or (OrList [OrElemString "Solanum tuberosum"]))))
isPotato(Item) :- species(Item,Species), match(Species, or, ["Solanum tuberosum"]).




/*
[Abstract Syntax]

EModule
    [ RuleStanza
        ( RuleDef1 ( RNum 1 )
            ( RID ( Ident "RuleOne" ) )
        ) RBNoop
    , RuleStanza
        ( RuleDefRuleNum ( RNum 2 ) )
        ( RBDeem
            [ ObjAttrAnd1
                ( OA_dots
                    [ ObjAttrElemIdent ( Ident "Item" )
                    , ObjAttrElemIdent ( Ident "isEdiblePotato" )
                    ]
                )
            , ObjAttrAnd1
                ( OA_dots
                    [ ObjAttrElemIdent ( Ident "Item" )
                    , ObjAttrElemIdent ( Ident "isTastyFood" )
                    ]
                )
            ]
            ( PEAnd
                ( PEOA
                    ( OA_dots
                        [ ObjAttrElemIdent ( Ident "Item" )
                        , ObjAttrElemIdent ( Ident "isPotato" )
                        ]
                    )
                )
                ( PEOA
                    ( OA_dots
                        [ ObjAttrElemIdent ( Ident "Item" )
                        , ObjAttrElemIdent ( Ident "isEdible" )
                        ]
                    )
                )
            )
        )
    , RuleStanza
        ( RuleDef1 ( RNum 3 )
            ( RID ( Ident "fertilize" ) )
        )
        ( RBDeem
            [ ObjAttrAnd1
                ( OA_dots
                    [ ObjAttrElemIdent ( Ident "Item" )
                    , ObjAttrElemIdent ( Ident "isPotato" )
                    ]
                )
            ]
            ( PEME
                ( ME_OA_JL
                    ( OA_dots
                        [ ObjAttrElemIdent ( Ident "Item" )
                        , ObjAttrElemIdent ( Ident "Species" )
                        ]
                    )
                    ( JL_Or
                        ( OrList [ OrElemString "Solanum tuberosum" ] )
                    )
                )
            )
        )
    ]

[Linearized tree]


RULE 1 RuleOne NOOP;
RULE 2 DEEM Item . isEdiblePotato AND Item . isTastyFood WHEN Item . isPotato AND Item . isEdible;
RULE 3 fertilize DEEM Item . isPotato WHEN Item . Species ~ ["Solanum tuberosum"];
*/

