#+TITLE: The home of the L4 DSL
#+STARTUP: content

This repo is in active development.

The only people writing L4 according to this spec are the core development team, and it doesn't even always work for them.

* L4 Language Family

L4 currently consists of:
- a developer-friendly /Natural/ syntax intended to be written in a spreadsheet "IDE"
- a semantically rigorous /Core/ syntax which lives in the repo ~smucclaw/baby-l4~

|            | Front-End IDE      | Parser               | How to Run                                     |
|------------+--------------------+----------------------+------------------------------------------------|
| Natural L4 | [[https://docs.google.com/spreadsheets/d/1qMGwFhgPYLm-bmoN2es2orGkTaTN382pG2z3RjZ_s-4/edit#gid=911811172][Legal Spreadsheets]] | lib/haskell/natural4 | cd lib/haskell/natural4                        |
|            |                    |                      | stack run -- --only native test/indented-1.csv |
|------------+--------------------+----------------------+------------------------------------------------|
| Core L4    |                    |                      |                                                |
|            |                    |                      |                                                |

|            | Target     | --only |
|------------+------------+--------|
| Natural L4 | Prolog     | prolog |
|            | Core       |        |
|            | ASP        |        |
|            | NLG        |        |
|            | Petri Nets | petri  |
|------------+------------+--------|
| Core l4    | ASP        |        |

* Natural L4

** Spreadsheet Interface

See [[https://docs.google.com/spreadsheets/d/1qMGwFhgPYLm-bmoN2es2orGkTaTN382pG2z3RjZ_s-4/edit#gid=911811172][Legal Spreadsheets]] for examples of "source code".

*Download as CSV*: grab a relevant tab off the spreadsheet.

#+begin_src bash
  cd lib/haskell/natural4
  stack test
  stack run -- --only native test/indented-1.csv
  stack run -- --only native test/pdpadbno-1.csv
#+end_src

If you're happy with this you can install the executable:

#+begin_src bash
  stack install
#+end_src

** Text-mode Interface

After the spreadsheet interface matures we will revisit support for a plaintext version of the language, to be supported in VS Code and Emacs via LSP. At this time we will write the BNF for the language.


