#+TITLE: Natural L4 Language Reference and Parser Guide

* Audience

This detailed documentation is intended for Haskell programmers developing the L4 compiler and related tools.

* Syntax Reference

The surface syntax of L4 is documented at
https://docs.google.com/spreadsheets/d/1leBCZhgDsn-Abg2H_OINGGv-8Gpf9mzuX1RR56v0Sss/edit#gid=1453008311

* Setup

Clone the entire repo https://github.com/smucclaw/dsl

* Prerequisites

The language is Haskell, and the build tool is Stack.

You do not need to install Haskell separately.

Just install Stack from http://haskellstack.org/. It will install an appropriate version of Haskell locally.

* Install the ~AnyAll~ library

In the ~dsl/lib/haskell/anyall/~ directory, run

#+begin_src bash
  stack install
#+end_src

* Install the ~Natural4~ Library

In the ~dsl/lib/haskell/natural4/~ directory, run

#+begin_src bash
  stack install
#+end_src

* Running Tests

In the ~dsl/lib/haskell/natural4/~ directory, when you run

#+begin_src bash
  stack test
#+end_src

You should get a screenful of green.

* Validating the Installation

In the ~dsl/lib/haskell/natural4/~ directory, if you run

#+begin_src bash
  stack run -- --workdir=workdir test/casestudypdpadbno-latest.csv
#+end_src

You should get a bunch of output onscreen, and you should get even more output inside the newly created directory ~workdir/~.

Specifically, inside the directory ~workdir/no-uuid/~ you should see a dozen or more output files, arranged in a directory tree.

If you browse those files you should see various representations of the PDPA DBNO encoding.

The spreadsheet version of that encoding is found at
https://docs.google.com/spreadsheets/d/1leBCZhgDsn-Abg2H_OINGGv-8Gpf9mzuX1RR56v0Sss/edit#gid=1779650637

L4 legal engineers working in the spreadsheet IDE can access those output files in the spreadsheet sidebar.

* fswatch

this one-liner will automatically rerun natural4 when it sees you have re-downloaded the CSV from google sheets.

#+begin_src bash
  fswatch -x /Volumes/1tb/mengwong/Downloads/ | perl -MFile::Copy  -nle 'if (my ($fn, $target) = /(Legal(?:SS | Spreadsheets - )(.*).csv) Created.*Renamed/) { for ($target) { print $target; $_ = lc $_; s/[^a-z]//g }; print $fn; print $target; move (qq(/Volumes/1tb/mengwong/Downloads/$fn), qq(/Users/mengwong/src/smucclaw/dsl/lib/haskell/natural4/test/$target-latest.csv)) && print(qq($fn -> $target)) && system(qq(cd src/smucclaw/dsl/lib/haskell/natural4; teedate=`date +%Y%m%d-%H%M%S`.txt; stack run -- --workdir=workdir test/$target-latest.csv > workdir/no-uuid/\$teedate; ln -sf \$teedate workdir/no-uuid/LATEST.txt; head workdir/no-uuid/LATEST.txt; echo done ))} BEGIN { $|++ }'
#+end_src
