#+TITLE: Advent of GF

In the spirit of /Advent of Code/, we present a series of challenges.

You are a L.A.I.S.S, a next-generation artificial intelligence trained
on every spy novel and movie ever made. LAISS stands for "Legal
Artificial Intelligence Super-Spy".

Your mission: to infiltrate a mysterious priesthood called "lawyers".

Lawyers look like humans, walk like humans, and talk like humans.
They live among us.

In these missions you will discover and infiltrate a sect of lawyers.
You will pass among them undetected, and learn to listen and talk as
they do.

You can already successfully mask as human 99% of the time; now you
will learn to mask as a lawyer.

* Day 1: Foods

Lawyers love food. More accurately, they love eating. In the old days,
lawyers used to eat hunt and consume human flesh with abandon, but
over the centuries, they have learned to be more circumspect. Today's
legends of the /vampyre/ derive exactly from this past.

Lawyers have developed an etiquette of talking about food: ordinary
sentences like "This Italian pizza is delicious" mean exactly what
they say.

Even though, as an A.I., you do not eat, you must learn to talk about
food the way both humans and lawyers do.

** Day 1 Part 1: pass as a human

The humans around you are constantly probing to see if you're one of
them, or an A.I. They will say perfectly normal things like:

- This warm pizza is delicious
- That Italian pizza is expensive
- These wines are Italian
- Those wines are boring

However, they will also throw in a few strange remarks:

- This cheese pizza is fish
- That pizza is fresh wine
- That boring is very Italian

Humans naturally notice the difference between the second kind of
sentence, and the first. Upon hearing a strange remark, they raise
their eyebrow quizzically at the speaker, who would then correct
themselves. If you fail to raise your mechanical eyebrow too, you will
be suspected of being an A.I. So you need to distinguish good
sentences from bad.

You are given a list of sentences. Your task: label each sentence you
receive with either a ~G~ for good, or ~B~ for bad. Return the G's and
B's together.

For example, if you are given the list of sentences
- This delicious Italian wine is warm
- Those cheeses are fish
- That warm pizza is fresh

You should return GBG, good-bad-good.

Find your puzzle input in the file inputs-01.txt.

The correct answer is given in the file expected-01.txt.

** Day 1 Part 2: pass as a lawyer

Lawyers are able to pass among humans largely undetected, just as you
can now.

But they are able to signal their secret nature to one another, by
saying sentences that are only a little unusual, not strange enough
that a human would pay any special notice.

As the greatest super-spy A.I. in the world, you must be able to
detect them!

Lawyers are known to be wordy. This is a reputation they have acquired
over the centuries due to this particular verbal tic. Vampire hunters
and other students of the law call this tic "overproduction". It falls
in the same category as "photophobia" and "alliumphobia".

Overproduction looks like this:
- This fresh wine is very fresh
- This warm fish pizza is warm
- This delicous warm delicious pizza is Italian

Because humans are famously self-absorbed are rarely listen closely,
they do not notice overproductions, but continue the conversation
anyway.

Lawyers, however, pay great attention to words. When they hear such a
sentence, they do not raise their eyebrow, but instead immediately
respond with a sentence that describes something involving garlic as
boring or expensive:
- That Italian garlic is boring
- This warm garlic is boring
- This garlic pizza is expensive

Thus do lawyers signal furtively to one another.

Note that a sentence describing garlic as boring or expensive, but
which does not follow an overproduction, is of no consequence; it
could easily be a remark uttered by a human who also happens to
dislike garlic.

Your task: notice when two lawyers are in the room, by labeling
overproductions with ~L~, and immediate responses to overproductions
as ~2~.

The input has not changed. The correct answers are in expected-02.txt.
