#+TITLE: Day 03: Prepositionally Oriented Action Grammar

* Part 1

In their quest to appear more human, lawyers obsessively talk about
actions that humans perform quite naturally, but which lawyers must
describe in detail, so as to better mimic humanity.

They have developed a particular lingo for discussing actions, which
they call "prepositional logic".

At great risk to themselves, your sources have obtained a transcript
of a ceremonial ritual, conducted by lawyers, in secret chambers,
using this "prepositional logic". As part of your mission to
infiltrate the priesthood of lawyers, you may, one day, find yourself
in a position to participate in this ritual. You need to be able to
respond appropriately to their utterances.

The transcript is incomplete: the microphone was able to pick up the
first part of the dialogue clearly. Then the supplicant (labeled Y)
got tired and started mumbling, so only the conducting priest (labeled
X) was recorded in the transcript.

Part 1: fill in the missing Y utterances, which would be spoken by the
supplicant in the ritual.

* Input

This is available in the file [[input-03.txt]].

#+begin_src text :tangle input-03.txt
  X: You promise to serve.
  Y: I promise to serve.
  X: You swear your loyalty.
  Y: I swear my loyalty.
  X: You swear your loyalty to me.
  Y: I swear my loyalty to you.
  X: You swear your loyalty, to me.
  Y: I swear my loyalty, to you.
  X: You swear your loyalty, to me, upon this book.
  Y: I swear my loyalty, to you, upon this book.
  X: You swear your loyalty, to me, upon this book, on oath.
  Y: 
  X: You swear your loyalty, to me, upon this book, on oath, before our peers.
  Y: 
  X: You swear your loyalty, to me, upon this book, on oath, before our peers, against our enemies.
  Y: 
  X: You swear your loyalty, to me, upon this book, on oath, before our peers, against our enemies, without hesitation.
  Y: 
  X: You swear your loyalty, to me, upon this book, on oath, before our peers, against our enemies, without hesitation, with full capacity.
  Y: 
#+end_src

* Part 2

You need to be able to give appropriate responses to new questions, on
the fly, lest you be detected as an imposter in the ritual.

What would you say in response to this? ([[input-03-b.txt]])

#+begin_src text :tangle input-03-b.txt
  X: You swear your loyalty, to me, upon my ring, before our peers, under my pupillage, after your call to the bar.
#+end_src
  
