% this file is autogenerated! -*- prolog -*-
% 1. tangle dsl/README.org using C-c C-v C-t
% 2. run (cat prelude.pl; ./mkProlog test1.l4) > potato.pl

:- use_module(library(yall)).

match(Elem, or,  List)   :- member(Elem, List).
match(Elem, and, List)   :- maplist(  [X]>>myeq(X,Elem), List).
match(Elem, xor, List)   :- partition([X]>>myeq(X,Elem), List, In, _Out), length(In,L), L = 1.
match(Elem, plain, List) :- match(Elem, or, List).
myeq(A,B) :- A == B.

% set up a couple of test potatoes
species(potato1, "Solanum tuberosum").
species(potato2, "Ipomoea batatas").
