FROM haskell:9.4.7-slim-buster as builder

COPY lib/haskell .

RUN apt update; \
    apt-get install -y --no-install-recommends \
    libpcre3-dev

RUN cd ./natural4 \
    && stack build \
    && stack install
