name:                l4-dsl-bnfc
version:             0.1.0.0
github:              "smucclaw/dsl"
license:             BSD3
author:              "Center for Computational Law, SMU"
maintainer:          "example@example.com"
copyright:           "2020 Center for Computational Law, SMU"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smucclaw/dsl#readme>

dependencies:
- base >= 4.7 && < 5
- pretty-simple
- array
- text
- regex-with-pcre
- containers
- fgl
- graphviz
- split
- gf

ghc-options:
- -Wall

build-tools:
- alex
- happy


library:
  source-dirs:
    - src-bnfc
    - src-l4

executables:
  l4:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - l4-dsl-bnfc

  showbug:
    main:                Main.hs
    source-dirs:         showbug
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - l4-dsl-bnfc

tests:
  l4-dsl-bnfc-test:
    main:                Spec.hs
    source-dirs:         test
    build-tools:
    - l4-dsl-bnfc:l4
    - l4-dsl-bnfc:showbug
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - l4-dsl-bnfc
    - process
    - tasty
    - tasty-hspec
    - tasty-program
    - tasty-golden
    - filepath
    - bytestring
    - text
