name:                LPAPCR34
version:             0.1.0.0
github:              "mengwong/LPAPCR34"
license:             BSD3
author:              "Wong Meng Weng"
maintainer:          "mwwong@smu.edu.sg"
copyright:           "2020"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mengwong/LPAPCR34#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- containers
- text
- boxes
- pretty-simple
- pretty
- optparse-simple
- prolog

library:
  source-dirs: src

executables:
  LPAPCR34-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LPAPCR34

tests:
  LPAPCR34-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LPAPCR34
