#+TITLE: LPAPCR34

In this case study, we formalize [[https://sso.agc.gov.sg/SL/LPA1966-S706-2015#pr34-][Section 34 of the Legal Profession (Professional Conduct) Rules 2015]].

See also [[https://github.com/smucclaw/fv/blob/taboo/Experiments/ProfessionalConductRule34/][the FV repo experiment]]. At some point these will be merged.

* Content

We represent all of Section 34 in L4. L4 (as currently defined) may not suffice to accurately and idiomatically represent Section 34. This use case therefore motivates improvement of the L4 language.

* Targets and Demonstrations

** Prolog
We create Prolog, in the spirit of "British Nationality Act as a Logic Program".

** Python
We automate the creation of a DocAssemble expert system.

We auto-generate Python to go into the DocAssemble YAML interview file.

** Formal Verification

We output to the model checking syntaxes shown in the [[https://github.com/smucclaw/fv/blob/taboo/Experiments/ProfessionalConductRule34/][FV repo]]. At some point these will be merged.

* L4 representation

** Section 1

1) A legal practitioner must not accept any executive appointment associated with any of the following businesses:
   a) any business which detracts from, is incompatible with, or derogates from the dignity of, the legal profession;
   b) any business which materially interferes with —
      1) the legal practitioner’s primary occupation of practising as a lawyer;
      2) the legal practitioner’s availability to those who may seek the legal practitioner’s services as a lawyer; or
      3) the representation of the legal practitioner’s clients;
   c) any business which is likely to unfairly attract business in the practice of law;
   d) any business which involves the sharing of the legal practitioner’s fees with, or the payment of a commission to, any unauthorised person for legal work performed by the legal practitioner;
   e) any business set out in the First Schedule;
   f) any business which is prohibited by —
      1) the Act;
      2) these Rules or any other subsidiary legislation made under the Act;
      3) any practice directions, guidance notes and rulings issued under section 71(6) of the Act; or
      4) any practice directions, guidance notes and rulings (relating to professional practice, etiquette, conduct and discipline) issued by the Council or the Society.


*** Let's talk commas!

=any business which detracts from, is incompatible with, or derogates from the dignity of, the legal profession=

Some style guides would argue that this comma is not strictly grammatical. Others would rebut that the last comma is necessary to disambiguate from

=any business which detracts from, is incompatible with, or derogates from, the dignity of the legal profession=

Before you read on: which makes more sense:
A. "detract from the legal profession"
B. "detract from the dignity of the legal profession"

If you answered B, you agree with the wording of the Second Schedule:

#+begin_quote
1. The business of the business entity —
(a) must not jeopardise the professional integrity, independence or competence of the legal practitioner; and
(b) must not detract from the standing and dignity of the legal profession.
#+end_quote

Analysis follows.

#+begin_example
// 1. the original phrasing invites this interpretation:
any business which - detracts from,
                   - is incompatible with,
                   or
                   - derogates from the dignity of,
                   the legal profession

// 2. Without a comma, it could mean the same as above...
any business which - detracts from,
                   - is incompatible with,
                     or
                   - derogates from the dignity of
                   the legal profession

// 3. ... or it could bind "the dignity of" differently, as in:
any business which - detracts from,
                   - is incompatible with,
                   or
                   - derogates from
                   the dignity of the legal profession

// 4. though if this were the intended interpretation we might place the comma differently:
any business which - detracts from,
                   - is incompatible with,
                   or
                   - derogates from,
                   the dignity of the legal profession

// can we think of a situation where
a business is compatible with the legal profession
but is incompatible with the dignity of the legal profession
?

scenario: a lawyer wants to make an indie movie on the side because of his lifelong interest in film. In the film, lawyers are portrayed negatively, as undignified. The movie is inspired in part by "Better Call Saul"
#+end_example


*** In L4, First Try

#+begin_src sql :noweb-ref section34-try1
  SECTION 34.1

   DEFINE 1base ISA DeonticRule
    GIVEN Predicate
    PARTY LegalPractitioner
    SHANT accept(role = ExecutiveAppointment)
    WHERE ExecutiveAppointment associated with Business
      AND Predicate (Business, LegalPractitioner)

   -- (expands to...)
 
   DEFINE 34.1.a ISA DeonticRule
    PARTY LegalPractitioner
    SHANT accept(role = ExecutiveAppointment)
    WHERE ExecutiveAppointment associated with Business
      AND Business detracts from legal_profession

   DEFINE 34.1.b ISA DeonticRule
    PARTY LegalPractitioner
    SHANT accept(role = ExecutiveAppointment)
    WHERE ExecutiveAppointment associated with Business
      AND Business materially_interferes ( with | primary_occupation
                                                | service_availability
                                                | client_representation
                                                of LegalPractitioner ) )

  -- note the preposition combinators are right associative

  RULE    34.1.a         -- syntax alternative 1: "or-list" with commas; the preps are partially applied
   RETURN 1base(Business [ detracts from
                         | is_incompatible with         -- LHS to a preposition
                         | derogates from dignity of ]  -- is a VPSlash
                         legal_profession )             -- "complement" to a preposition

   RETURN 1base(Business detracts from legal_profession )
   RETURN 1base(Business [ detracts from , is_incompatible with ]
                         [ legal_profession, financial_profession ] )


                       -- Applicatives: [ a, b, c ] <*> pure legal_profession

  RULE    34.1.b                                -- syntax 2: experimental
   RETURN 1base(Business materially_interferes ( with | primary_occupation
                                                      | service_availability
                                                      | client_representation
                                                      of LegalPractitioner ) )

  RULE    34.1.c                 -- consider right associativity
   RETURN 1base(Business likely ( to unfairly_attract_business in practice of law ) )

  RULE    34.1.d                    -- syntax 3: "any" of a normal [,,,] list
   RETURN 1base(Business involves ( any [ sharing_fees with
                                        , (payment of commission to)
                                        ] unauthorized_person
                                    for (legal_work performed by LegalPractitioner ) ) )


  RULE    34.1.e
   RETURN 1base(FirstSchedule(Business))


   -- syntax 4: with more explicit equals signs, resembling function params; can we get rid of them?
  RULE    34.1.f
   RETURN 1base(Business prohibitedByUsualSuspects)

  DEFINE  prohibitedByUsualSuspects
   SCOPE  SECTION 34
   HIDDEN true
   RETURN prohibited (by = [ the_Act
                           , [ these_rules | subsidiary_legislation ]
                           , any [ practice_directions , guidance_notes U rulings ]
                             issued (under = section 71.6 of Act)
                           | any [ practice_directions , guidance_notes U rulings ]
                             relating (to = [ professional_practice, etiquette, conduct U discipline ])
                             issued   (by = [ the_Council | the_Society ] )
                           ] )

#+end_src

*** Second Try, all in one giant block

**** As L4
#+begin_src text :tangle test/section34-1.l4
  SECTION 34.1 :en:"Thirty Four, Part One"

     RULE 34.1.a ISA DeonticRule
    PARTY LegalPractitioner
    SHANT accept(Executive_appointment)
     WHEN associatedWith(Executive_appointment, Business)
      AND any [ Business [ detracts_from
                         , is_incompatible_with
                         | derogates_from ] the_dignity_of the_legal_profession
              , Business materially_interferes_with [ LegalPractitioner's primary_occupation_of_practising_as_a_lawyer
                                                    , availability_to those_who may_seek LegalPractitioner's services_as_a_lawyer
                                                    | the_representation_of LegalPractitioner's clients ]
              , Business is_likely_to unfairly attract_business_in the_practice_of_law
              , Business involves [ the_sharing_of LegalPractitioner's fees with
                                  | the_payment_of a_commission to ]
                                  (any unauthorised_person)
                                  for (legal_work performed_by LegalPractitioner)
              , Business is in FirstSchedule
              , Business is prohibited_by [ the_Act
                                          , [ these_Rules
                                            | any_other_subsidiary_legislation
                                              made_under the_Act ]
                                          , any [ practice_directions
                                                , guidance_notes
                                                U rulings ]
                                            issued_under section_71(6)_of the_Act
                                          | any [ practice_directions
                                                , guidance_notes
                                                U rulings ]
                                            relating_to [ professional_practice
                                                        , etiquette
                                                        , conduct
                                                        & discipline ]
                                            issued_by [ the_Council | the_Society ]
                                          ]
              ]
#+end_src

**** Our front-end uses a few simple types

#+begin_src haskell :noweb-ref 34-types
  data Conj = AndC | OrC | CommaC | AnyC | UnionC | IntersectC | RunOn
    deriving (Show, Eq)

  data TermExpr = TEString NLStr               -- ideally spaceless but can contain spaces
                | TEList Conj [TermExpr]       -- any [foo,bar]   [foo, bar | baz]   [foo & bar]
                | TECompound TermExpr TermExpr -- foo(bar, baz) what Prolog calls a compound term, but looks like a function to everyone else
                | TEPrep NLStr                 -- "to" "for" "with" "of" "from" "by"
                | TE2 TermExpr BinOp TermExpr  -- foo + bar, foo = bar
    deriving (Show, Eq)

  type NLTag = (String,String)
  data NLStr = NL { ex :: String, tags :: [NLTag] } deriving (Show, Eq)
  data BinOp = Plus | Minus | Times | Divide | Pow | Tilde deriving (Show, Eq)

  data Stm = Section          NLStr
           | DeonticRule      NLStr DRuleBody
           | ConstitutiveRule NLStr CRuleBody deriving (Show, Eq)

  data Deontic = DMust | DMay | DShant deriving (Show, Eq)

  data DRuleBody = DRule { party  :: NLStr
                         , dmodal :: Deontic
                         , action :: TermExpr
                         , when   :: Maybe TermExpr
                         } deriving (Show, Eq)
    -- no hence, no lest

  data CRuleBody = CRule { item :: NLStr
                         , body :: TermExpr
                         , when :: Maybe TermExpr
                         } deriving (Show, Eq)

#+end_src

**** The Parser
#+begin_src haskell :noweb-ref 34-parser
  -- an L4 document is a list of stanzas
  parseL4 :: Parser [Stm]
  parseL4 = do
    stm <- parseStm
    rhs <- parseL4
    eof
    return (stm : rhs)

  -- a stanza
  parseStm :: Parser Stm
  parseStm = do
    many newline
    stm <- choice [ try (Section          <$> (lexeme "SECTION" *> parseNLStr))
                  , try parseDeonticRule
                  , try parseConstitutiveRule
                  ]
    return stm

  -- RULE PARTY X MUST Y
  parseDeonticRule :: Parser Stm
  parseDeonticRule = do
    ruleName <- space *> lexeme "RULE"    *> parseNLStr <* lexeme "ISA" <* lexeme "DeonticRule" <* some newline
    party    <- space *> lexeme "PARTY"   *> parseNLStr <*                                         some newline
    dmodal   <- space *> lexeme (DMust  <$ "MUST" <|>
                                 DMay   <$ "MAY"  <|>
                                 DShant <$ "SHANT")
    action   <-          lexeme parseTermExpr <* some newline
    when     <- (Just <$> space *> lexeme "WHEN" *> parseTermExpr) <|> (Nothing <$ empty)
    return (DeonticRule ruleName (DRule party dmodal action when))

  -- DEFINE X IS BLAH
  parseConstitutiveRule :: Parser Stm
  parseConstitutiveRule = do
    ruleName <- space *> lexeme "RULE"    *> parseNLStr <* lexeme "ISA" <* lexeme "ConstitutiveRule" <* some newline
    item     <- space *> lexeme "DEFINE"  *> parseNLStr <*                                         some newline
    body     <-          lexeme parseTermExpr <* some newline
    when     <- (Just <$> space *> lexeme "WHEN" *> parseTermExpr ) <|> (Nothing <$ empty)
    return (DeonticRule ruleName (DRule party dmodal action when))

  -- SomeString :en:"Some String"
  parseNLStr :: Parser NLStr
  parseNLStr = do
    exPart    <- lexeme $ some (alphaNumChar <|> char '.')
    tagsPart  <- many (lexeme parseTag)
    return $ NL exPart tagsPart

  -- :en:"Some String"
  parseTag :: Parser NLTag
  parseTag = do
    lhs <- between (char ':') (char ':') (some alphaNumChar)
    rhs <- stringLiteral
    return (lhs, rhs)

  -- sooner or later we will need to think about https://github.com/glebec/left-recursion
  parseTermExpr :: Parser TermExpr
  parseTermExpr = return $ TEString (NL "burf" [])
    
#+end_src

**** A simple app calls the parser and prints the AST

#+begin_src haskell :noweb-ref 34-app
  someFunc :: IO ()
  someFunc = do
    myinput <- getContents
    let ast = case parse parseL4 "parsing L4 toplevel" (pack myinput) of
                Left  someError  -> error $ errorBundlePretty someError
                Right rhs -> rhs
    -- print ast
    print ast
#+end_src

**** Haskell Infrastructure

#+begin_src haskell parse-341 :noweb yes :tangle src/Lib.hs

  {-# LANGUAGE OverloadedStrings #-}
  {-# LANGUAGE ScopedTypeVariables #-}
  {-# LANGUAGE DuplicateRecordFields #-}

  module Lib where

  import Text.Megaparsec
  import Text.Megaparsec.Char
  import qualified Text.Megaparsec.Char.Lexer as L
  import Data.Text (Text, pack, unpack)
  import Data.Void
  import Data.List (nub, permutations, sort, sortOn, intercalate)
  import Data.Char (toLower)
  import Control.Monad (forM_)
  import qualified Text.PrettyPrint.Boxes as Bx
  type Parser = Parsec Void Text

  sc :: Parser ()
  sc = L.space space1 (L.skipLineComment "//") (L.skipBlockComment "/*" "*/")

  lexeme :: Parser a -> Parser a
  lexeme = L.lexeme sc

  stringLiteral = char '"' >> manyTill L.charLiteral (char '"')

  <<34-types>>
  <<34-parser>>
  <<34-app>>

#+end_src

** Section 2

2) Subject to paragraph (1), a legal practitioner in a Singapore law practice (called in this paragraph the main practice) may accept an executive appointment in another Singapore law practice (called in this paragraph the related practice), if the related practice is connected to the main practice in either of the following ways:
   a) every legal or beneficial owner of the related practice is the sole proprietor, or a partner or director, of the main practice;
   b) the legal practitioner accepts the executive appointment as a representative of the main practice in the related practice, and the involvement of the main practice in the related practice is not prohibited by any of the following:
      1) the Act;
      2) these Rules or any other subsidiary legislation made under the Act;
      3) any practice directions, guidance notes and rulings issued under section 71(6) of the Act;
      4) any practice directions, guidance notes and rulings (relating to professional practice, etiquette, conduct and discipline) issued by the Council or the Society.

We use a different syntactic style here, where the entire paragraph is made a single RULE; the parts are labeled.

#+begin_src sql :noweb-ref section34
  SECTION 34.2
   RULE       34.2
    SUBJECTTO 34.1
        GIVEN SingaporeLawPractice1 :en:"the main practice"    AS MainP
              SingaporeLawPractice2 :en:"the related practice" AS RelatedP
        PARTY LegalPractitioner
          MAY accept (role = ExecutiveAppointment) in SingaporeLawPractice2 AS Acceptance
         WHEN [ :label:34.2.a
                FORALL Owner2 in [ legal | beneficial ] Owner of SingaporeLawPractice2 {
                  Owner2 is [ soleProprietor | partner | director ] of SingaporeLawPractice1
                }
              | :label:34.2.b
                Acceptance as representative
                              (of SingaporeLawPractice1
                              ,in SingaporeLawPractice2)
                  -- this is not a 34.2.c because it's a OR (b1 AND b2)
                  AND NOT (Involvement (of MainP, in RelatedP)
                           prohibitedByUsualSuspects)
              ]
#+end_src         

every legal or beneficial owner of the related practice is

- the sole proprietor, or a partner or director, of the main practice;
- the sole proprietor, a partner, or a director of the main practice;

BUT NOT

- the sole proprietor, partner, or director of the main practice;
  (implies there is only one partner / director)

- the sole proprietor, a partner, or director of the main practice;
  (ungrammatical, "director" violates parallel structure)

- "is a sole proprietor, partner, or director of the main practice"

** Section 3

3) Subject to paragraph (1), a legal practitioner may accept an executive appointment in a business entity which provides law-related services.

** Section 4

** Section 5

*** Let's talk types!

There is synecdoche going on here -- 34.1.b is a predicate constraining businesses, but 34.5 casts it to a deontic deny, implicitly including the context of the introductory text of 34.1 above in the "parent".

** Section 6

* Language Notes

** Prepositional Style and Infix Operators

Gosh, prepositions are complicated. Here we'll try to do a sort of Rosetta Stone between representations of the same ideas in multiple languages.

https://en.wikipedia.org/wiki/List_of_English_prepositions

Let's say we follow Prolog tradition for a moment: variables are =Upper= and functions are =lower=.

Color = { red, green, blue }
val red   = "red"
val green = "green"
val blue  = "blue"

val potatoColor : Color = green

Suppose we have a simple clause that says, *if potatoColor is red, blue, or green*. Semantically, the clause is a Boolean predicate.
- Python     :: potatoColor in     [ red, blue, green ]
- Javascript :: [ red, blue, green ].indexOf(potatoColor) >= 0
- Haskell    :: potatoColor `elem` [ red, blue, green ]
- Prolog     :: member(   PotatoColor, [ red, blue, green ]).
- Prolog     :: memberchk(PotatoColor, [ red, blue, green ]).      (semidet)
- L4         :: potatoColor is     [ red, blue | green ] -- NLG produces "potatoColor is red, blue, or green"
- L4         :: potatoColor is any [ red, blue U green ] -- NLG produces "potatoColor is any of red, blue, and green"

potato.color is [red, blue | green]

potato is [yellow, cooked & salted]

What do we do about more complex phrases? Let's consider a sentence which expresses a list -- a list of things, filtered through a couple of predicates:
- English :: *any guidance notes relating to conduct issued by the Council*
- GF      ::
#+begin_src gf
(AnyDet (NounVP (mkNoun "guidance note" Pl)
                             (mkAdvP "relating" "to" (mkN "conduct"))
                             (mkAdvP "issued"   "by" (theDet (mkN "Council")))))
#+end_src
- Python  :: [ x in guidanceNotes
               if  "conduct" in x.relatingTo
               and "Council" in x.issuedBy ]
- Javascript :: guidanceNotes.filter(lambda x => ...)
- Prolog :: gnRule(GN) :- relatesTo(GN, conduct), issuedBy(GN, theCouncil).
- L4 :: (any guidanceNotes (relating TO conduct (issued BY theCouncil)))

Let's throw a couple more bits into the mix:

- English :: *any practice directions, guidance notes and rulings (relating to professional practice, etiquette, conduct and discipline) issued by the Council or the Society.*

Here we have ambiguity -- does the "relating to" constraint attach to "rulings" only, or to all of "practice directions, guidance notes and rulings"? The nice thing about a formal syntax is that it saves us from even having to ask that question.

- L4 :: wrong:
#+begin_src sql
      any [ practice_directions, guidance_notes U rulings ]
          relating to ( [ professional_practice, etiquette, conduct U discipline ]
                        issued   by [ the_Council | the_Society ] )
#+end_src

- L4 :: right:
#+begin_src sql
      any [ practice_directions, guidance_notes U rulings ]
          relating to [ professional_practice, etiquette, conduct U discipline ]
          issued   by [ the_Council | the_Society ]
#+end_src

#+begin_src haskell
  [ thing <- [ x, y, z ]
  | thing `relatingTo` [...]
  , thing `issuedBy`   [...]
  ]
#+end_src

** Right Associativity and Transitive Prepositions

Let's take an entity defined by its constraint:

- English :: Business likely to unfairly attract business in practice of law
- L4 :: business likely to unfairly_attract_business in practice of law

Here's how the right-associativity binds:

                                                   N2?
                                                   VPSlash  PrepOf Comp
                     VPSlash               PrepIn (Comp               )
          VPSlash PrepTo  (Comp                                        )
business (likely to (unfairly_attract_business in (practice of     law)))

Gosh, it looks like the prepositions here are binary infix operators:

| left                      | binary preposition | right  | bound to term |
|---------------------------+--------------------+--------+---------------|
| practice                  | of                 | law    | pol           |
| unfairly_attract_business | in                 | pol    | uabpol        |
| likely                    | to                 | uabpol | l2uabpol      |

So our algorithm looks for keyword prepositions; the stuff to the right is the complement; the word, clause, or array to the left of the preposition is the LHS.

** Prepositional Groups: when do we use commas and parentheses?

#+begin_quote
Finally, a preposition that consists of two or more words is called a complex preposition.[10] It is a matter of debate as to whether these groups of words each function as a single preposition (the complex preposition analysis) or the initial preposition simply takes a complement that contains another preposition. Traditional grammars and some dictionaries take this complex preposition approach, but grammars informed by work in linguistics vary in how they address these groups of words.
#+end_quote

Suppose we have: =Business [ detracts from , is_incompatible with | derogates from ] dignity of legal_profession=



                         
** Notes: Simplification

The compiler automatically expands, then refactors, 34.1 to simplify the expression to be readable, from

#+begin_example
step 1:
  - base = a b c(...)
  - base(1 2)
  - base(3 4)
  - base(5 6)
  - base(7 8)

step 2:
  - a b c 1 2
  - a b c 3 4
  - a b c 5 6
  - a b c 7 8

step 3:
- a b c (any [1 2, 3 4, 5 6, 7 8])
#+end_example

  
  
* Source Text

** Section 34

https://sso.agc.gov.sg/SL/LPA1966-S706-2015#pr34-

Paragraph numbering scheme is 1.a.i. Roman numerals were converted to arabic to be kinder to org-mode.

1) A legal practitioner must not accept any executive appointment associated with any of the following businesses:
   a) any business which detracts from, is incompatible with, or derogates from the dignity of, the legal profession;
   b) any business which materially interferes with —
      1) the legal practitioner’s primary occupation of practising as a lawyer;
      2) the legal practitioner’s availability to those who may seek the legal practitioner’s services as a lawyer; or
      3) the representation of the legal practitioner’s clients;
   c) any business which is likely to unfairly attract business in the practice of law;
   d) any business which involves the sharing of the legal practitioner’s fees with, or the payment of a commission to, any unauthorised person for legal work performed by the legal practitioner;
   e) any business set out in the First Schedule;
   f) any business which is prohibited by —
      1) the Act;
      2) these Rules or any other subsidiary legislation made under the Act;
      3) any practice directions, guidance notes and rulings issued under section 71(6) of the Act; or
      4) any practice directions, guidance notes and rulings (relating to professional practice, etiquette, conduct and discipline) issued by the Council or the Society.

2) Subject to paragraph (1), a legal practitioner in a Singapore law practice (called in this paragraph the main practice) may accept an executive appointment in another Singapore law practice (called in this paragraph the related practice), if the related practice is connected to the main practice in either of the following ways:
   a) every legal or beneficial owner of the related practice is the sole proprietor, or a partner or director, of the main practice;
   b) the legal practitioner accepts the executive appointment as a representative of the main practice in the related practice, and the involvement of the main practice in the related practice is not prohibited by any of the following:
      1) the Act;
      2) these Rules or any other subsidiary legislation made under the Act;
      3) any practice directions, guidance notes and rulings issued under section 71(6) of the Act;
      4) any practice directions, guidance notes and rulings (relating to professional practice, etiquette, conduct and discipline) issued by the Council or the Society.

3) Subject to paragraph (1), a legal practitioner may accept an executive appointment in a business entity which provides law-related services.

4) Subject to paragraph (1), a legal practitioner (not being a locum solicitor) may accept an executive appointment in a business entity which does not provide any legal services or law-related services, if all of the conditions set out in the Second Schedule are satisfied.

5) Despite paragraph (1)(b), but subject to paragraph (1)(a) and (c) to (f), a locum solicitor may accept an executive appointment in a business entity which does not provide any legal services or law-related services, if all of the conditions set out in the Second Schedule are satisfied.

6) Except as provided in paragraphs (2) to (5) —
   a) a legal practitioner in a Singapore law practice must not accept any executive appointment in another Singapore law practice; and
   b) a legal practitioner must not accept any executive appointment in a business entity.

7) To avoid doubt, nothing in this rule prohibits a legal practitioner from accepting any appointment in any institution set out in the Third Schedule.

8) To avoid doubt, this rule does not authorise the formation of, or regulate —
   a) any related practice referred to in paragraph (2); or
   b) any business entity referred to in paragraph (3), (4) or (5).

9) In this rule and the First to Fourth Schedules —
   - "business" :: includes any business, trade or calling in Singapore or elsewhere, whether or not for the purpose of profit, but excludes the practice of law;
   - "business entity" ::
     a) includes any company, corporation, partnership, limited liability partnership, sole proprietorship, business trust or other entity that carries on any business; but
     b) excludes any Singapore law practice, any Joint Law Venture, any Formal Law Alliance, any foreign law practice and any institution set out in the Third Schedule;
   - "executive appointment" :: means a position associated with a business, or in a business entity or Singapore law practice, which entitles the holder of the position to perform executive functions in relation to the business, business entity or Singapore law practice (as the case may be), but excludes any non‑executive director or independent director associated with the business or in the business entity;
   - "law-related service" :: means any service set out in the Fourth Schedule, being a service that may reasonably be performed in conjunction with, and that is in substance related to, the provision of any legal service.


** First Schedule

Rule 34(1)(e) and (9)

PROHIBITED BUSINESSES

1.	Housing or estate agency business

2.	Debt collection business

** Second Schedule

Rule 34(4), (5) and (9)

CONDITIONS FOR ACCEPTING EXECUTIVE APPOINTMENT IN BUSINESS ENTITY

1. The business of the business entity —
   a) must not jeopardise the professional integrity, independence or competence of the legal practitioner; and
   b) must not detract from the standing and dignity of the legal profession.

2. The business entity must not be held out or described in such a way as to suggest —
   a) that the business entity is a law practice; or
   b) that any legal practitioner in the business entity provides services, carries on business, or is employed, as a regulated legal practitioner.

3. The involvement of the legal practitioner in the business entity must not impair, and must not be in conflict with, the legal practitioner’s duties —
   a) in the law practice in which the legal practitioner practises; or
   b) to any client of that law practice.

4. The files, records and accounts of the business entity must be kept separate from and independent of the files, records and accounts of the law practice in which the legal practitioner practises.

5. Where, in the course of dealing with the law practice in which the legal practitioner practises, a client of that law practice deals with, or is referred by that law practice to, the business entity, the legal practitioner must make full and frank disclosure of all of the following matters to the client:
   a) the relationship (if any) between the business entity and each of the following:
      1) that law practice;
      2) every legal practitioner in that law practice who has any interest in the business entity;
   b) the financial or other interests of each of the following in the business entity:
      i) that law practice;
      ii) every legal practitioner in that law practice who has any interest in the business entity;
   c) that the statutory protection conferred on a client of a law practice under the Act (including but not limited to compulsory professional indemnity insurance coverage and the Compensation Fund maintained under section 75 of the Act), or under any subsidiary legislation made under the Act, may not be available to a customer of the business entity.

6. The client account of the law practice in which the legal practitioner practises, and any other account of that law practice used to hold money for a client of that law practice, must not be used to hold money for the business entity in its capacity as such, or for any customer of the business entity in the customer’s capacity as such.

7. Each account of the business entity must not be used to hold money for the law practice in which the legal practitioner practises in that law practice’s capacity as such, or for any client of that law practice in the client’s capacity as such.

8.
   1. The business entity must conduct its business at an address that is separate and distinct from the address of the law practice in which the legal practitioner practises.
   2. However —
      a) both addresses may be in the same building; and
      b) the business entity is not to be treated as conducting its business at an address by reason only that the address is the address of the registered office of the business entity.


** Third Schedule

Rule 34(7) and (9)

INSTITUTIONS IN WHICH LEGAL PRACTITIONER MAY ACCEPT ANY APPOINTMENT

1. The Society
2. The Academy
3. The Institute
4. The National University of Singapore
5. The Singapore Management University
5A. The Singapore University of Social Sciences [S 82/2018 wef 12/02/2018]
6. Any charity registered under section 5 of the Charities Act (Cap. 37)

** Fourth Schedule

Rule 34(9)

LAW-RELATED SERVICES

1. Any intellectual property service, including the registration (where applicable), and the provision of consultancy and advice on the management and enforcement, of copyright, trade marks, patents, designs, plant varieties and any other category of intellectual property referred to in the Agreement on Trade-Related Aspects of Intellectual Property Rights
2. Any tax service, including tax consultancy and advice
3. Any trust business or trust business service as defined in section 2 of the Trust Companies Act (Cap. 336)
4. Any company secretarial service, including the establishment and incorporation of a company
5. Any service as a continuing sponsor company for an entity any shares of which are listed for quotation on the Singapore Exchange Catalist
6. Any administrative, management, property or other service provided exclusively to a law practice or to a business entity referred to in rule 34(3), (4) or (5)
7. Any forensic investigation, document management or discovery service, or any other service relating to litigation support
8. Any voluntary liquidation service



