* preface
:PROPERTIES:
:VISIBILITY: folded
:END:

natural4> test (suite: natural4-test, args: --match "/our new parser/indent-2-c-3/")

* Tokens
Lib preprocessor: inserting EOL between Other "this is a label" and Other "mid3"
( "top1" ) OR ( "top2" ) OR
    ( "this is a label" EOL ( "mid3" ) OR ( "mid4" ) )
* main
:PROPERTIES:
:VISIBILITY: children
:END:

** / expr pParamText                                                                                                    :1_2:GoDeeper:
*** / expression                                                                                                       :1_2:GoDeeper:
**** / labelPrefix                                                                                                    :1_2:GoDeeper:
labelPrefix> IN: ( "top1" ) OR ( "top2" ) OR ( "this is a <…>
labelPrefix> MATCH (EERR): <EMPTY>
labelPrefix> ERROR:
labelPrefix> offset=0:
labelPrefix> unexpected (
labelPrefix> expecting Other text

**** / term p                                                                                                         :1_2:GoDeeper:
***** / term p/notLabelTerm                                                                                          :1_2:GoDeeper:
****** / term p/2:someIndentation expr p                                                                            :1_2:GoDeeper:
******* / someIndentation                                                                                          :1_2:GoDeeper:
******** / myindented: consuming GoDeeper                                                                         :1_2:GoDeeper:
myindented: consuming GoDeeper> IN: ( "top1" ) OR ( "top2" ) OR ( "this is a <…>
myindented: consuming GoDeeper> MATCH (COK): (
myindented: consuming GoDeeper> VALUE: (GoDeeper,[])

******** \ myindented: consuming GoDeeper has returned GoDeeper                                                    :1_2:Other "top1:
******** / manyIndentation/leaf?                                                                                   :1_2:Other "top1:
********* / expression                                                                                            :1_2:Other "top1:
********** / labelPrefix                                                                                         :1_2:Other "top1:
labelPrefix> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
labelPrefix> MATCH (EERR): <EMPTY>
labelPrefix> ERROR:
labelPrefix> offset=2:
labelPrefix> unexpected )

********** / term p                                                                                              :1_2:Other "top1:
*********** / term p/notLabelTerm                                                                               :1_2:Other "top1:
************ / term p/2:someIndentation expr p                                                                 :1_2:Other "top1:
************* / someIndentation                                                                               :1_2:Other "top1:
************** / myindented: consuming GoDeeper                                                              :1_2:Other "top1:
myindented: consuming GoDeeper> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
myindented: consuming GoDeeper> MATCH (EERR): <EMPTY>
myindented: consuming GoDeeper> ERROR:
myindented: consuming GoDeeper> offset=1:
myindented: consuming GoDeeper> unexpected "top1"
myindented: consuming GoDeeper> expecting (

someIndentation> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
someIndentation> MATCH (EERR): <EMPTY>
someIndentation> ERROR:
someIndentation> offset=1:
someIndentation> unexpected "top1"
someIndentation> expecting (

term p/2:someIndentation expr p> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
term p/2:someIndentation expr p> MATCH (EERR): <EMPTY>
term p/2:someIndentation expr p> ERROR:
term p/2:someIndentation expr p> offset=1:
term p/2:someIndentation expr p> unexpected "top1"
term p/2:someIndentation expr p> expecting (

************ / term p/3:plain p                                                                                :1_2:Other "top1:
************* / pParamText                                                                                    :1_2:Other "top1:
************** / pParamText(flat) first line: pKeyValues                                                     :1_2:Other "top1:
*************** / pKeyValuesAka                                                                             :1_2:Other "top1:
**************** / slAKA                                                                                   :1_2:Other "top1:
***************** / $*|                                                                                   :1_2:Other "top1:
****************** / slAKA base                                                                          :1_2:Other "top1:
******************* / slKeyValues                                                                       :1_2:Other "top1:
******************** / $*|                                                                             :1_2:Other "top1:
********************* / someSL                                                                        :1_2:Other "top1:
someSL> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
someSL> MATCH (COK): "top1"
someSL> VALUE: ((["top1"],0),[])

********************* \ someSL has returned (["top1"],0)                                               :2_2:UnDeeper:
$*|> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
$*|> MATCH (COK): "top1"
$*|> VALUE: ((["top1"],0),[])

******************** \ $*| has returned (["top1"],0)                                                    :2_2:UnDeeper:
******************** / |>>/recurse                                                                      :2_2:UnDeeper:
|>>/recurse> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=2:
|>>/recurse> unexpected )
|>>/recurse> expecting (

******************** / |>>/base                                                                         :2_2:UnDeeper:
********************* / |?| optional something                                                         :2_2:UnDeeper:
********************** / |>>/recurse                                                                  :2_2:UnDeeper:
|>>/recurse> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=2:
|>>/recurse> unexpected )
|>>/recurse> expecting (

********************** / |>>/base                                                                     :2_2:UnDeeper:
*********************** / slTypeSig                                                                  :2_2:UnDeeper:
************************ / $>|                                                                      :2_2:UnDeeper:
$>|> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
$>|> MATCH (EERR): <EMPTY>
$>|> ERROR:
$>|> offset=2:
$>|> unexpected )
$>|> expecting :: or IS

slTypeSig> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
slTypeSig> MATCH (EERR): <EMPTY>
slTypeSig> ERROR:
slTypeSig> offset=2:
slTypeSig> unexpected )
slTypeSig> expecting :: or IS

|>>/base> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/base> MATCH (EERR): <EMPTY>
|>>/base> ERROR:
|>>/base> offset=2:
|>>/base> unexpected )
|>>/base> expecting :: or IS

|?| optional something> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|?| optional something> MATCH (EOK): <EMPTY>
|?| optional something> VALUE: ((Nothing,0),[])

********************* \ |?| optional something has returned (Nothing,0)                                :2_2:UnDeeper:
********************* > |>>/base got Nothing                                                           :2_2:UnDeeper:
|>>/base> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/base> MATCH (EOK): <EMPTY>
|>>/base> VALUE: ((Nothing,0),[])

******************** \ |>>/base has returned (Nothing,0)                                                :2_2:UnDeeper:
slKeyValues> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
slKeyValues> MATCH (COK): "top1"
slKeyValues> VALUE: ((("top1" :| [],Nothing),0),[])

******************* \ slKeyValues has returned (("top1" :| [],Nothing),0)                                :2_2:UnDeeper:
slAKA base> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
slAKA base> MATCH (COK): "top1"
slAKA base> VALUE: ((("top1" :| [],Nothing),0),[])

****************** \ slAKA base has returned (("top1" :| [],Nothing),0)                                   :2_2:UnDeeper:
$*|> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
$*|> MATCH (COK): "top1"
$*|> VALUE: ((("top1" :| [],Nothing),0),[])

***************** \ $*| has returned (("top1" :| [],Nothing),0)                                            :2_2:UnDeeper:
***************** / |>>/recurse                                                                            :2_2:UnDeeper:
|>>/recurse> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=2:
|>>/recurse> unexpected )
|>>/recurse> expecting (

***************** / |>>/base                                                                               :2_2:UnDeeper:
****************** / slAKA optional akapart                                                               :2_2:UnDeeper:
******************* / |?| optional something                                                             :2_2:UnDeeper:
******************** / |>>/recurse                                                                      :2_2:UnDeeper:
|>>/recurse> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=2:
|>>/recurse> unexpected )
|>>/recurse> expecting (

******************** / |>>/base                                                                         :2_2:UnDeeper:
********************* / PAKA/akapart                                                                   :2_2:UnDeeper:
********************** / $>|                                                                          :2_2:UnDeeper:
*********************** / Aka Token                                                                  :2_2:UnDeeper:
Aka Token> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
Aka Token> MATCH (EERR): <EMPTY>
Aka Token> ERROR:
Aka Token> offset=2:
Aka Token> unexpected )
Aka Token> expecting AKA

$>|> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
$>|> MATCH (EERR): <EMPTY>
$>|> ERROR:
$>|> offset=2:
$>|> unexpected )
$>|> expecting AKA

PAKA/akapart> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
PAKA/akapart> MATCH (EERR): <EMPTY>
PAKA/akapart> ERROR:
PAKA/akapart> offset=2:
PAKA/akapart> unexpected )
PAKA/akapart> expecting AKA

|>>/base> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/base> MATCH (EERR): <EMPTY>
|>>/base> ERROR:
|>>/base> offset=2:
|>>/base> unexpected )
|>>/base> expecting AKA

|?| optional something> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|?| optional something> MATCH (EOK): <EMPTY>
|?| optional something> VALUE: ((Nothing,0),[])

******************* \ |?| optional something has returned (Nothing,0)                                    :2_2:UnDeeper:
slAKA optional akapart> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
slAKA optional akapart> MATCH (EOK): <EMPTY>
slAKA optional akapart> VALUE: ((Nothing,0),[])

****************** \ slAKA optional akapart has returned (Nothing,0)                                      :2_2:UnDeeper:
****************** > |>>/base got Nothing                                                                 :2_2:UnDeeper:
|>>/base> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/base> MATCH (EOK): <EMPTY>
|>>/base> VALUE: ((Nothing,0),[])

***************** \ |>>/base has returned (Nothing,0)                                                      :2_2:UnDeeper:
***************** / |>>/recurse                                                                            :2_2:UnDeeper:
|>>/recurse> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=2:
|>>/recurse> unexpected )
|>>/recurse> expecting (

***************** / |>>/base                                                                               :2_2:UnDeeper:
****************** / slAKA optional typically                                                             :2_2:UnDeeper:
******************* / |?| optional something                                                             :2_2:UnDeeper:
******************** / |>>/recurse                                                                      :2_2:UnDeeper:
|>>/recurse> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=2:
|>>/recurse> unexpected )
|>>/recurse> expecting (

******************** / |>>/base                                                                         :2_2:UnDeeper:
********************* / typically                                                                      :2_2:UnDeeper:
********************** / $>|                                                                          :2_2:UnDeeper:
$>|> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
$>|> MATCH (EERR): <EMPTY>
$>|> ERROR:
$>|> offset=2:
$>|> unexpected )
$>|> expecting TYPICALLY

typically> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
typically> MATCH (EERR): <EMPTY>
typically> ERROR:
typically> offset=2:
typically> unexpected )
typically> expecting TYPICALLY

|>>/base> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/base> MATCH (EERR): <EMPTY>
|>>/base> ERROR:
|>>/base> offset=2:
|>>/base> unexpected )
|>>/base> expecting TYPICALLY

|?| optional something> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|?| optional something> MATCH (EOK): <EMPTY>
|?| optional something> VALUE: ((Nothing,0),[])

******************* \ |?| optional something has returned (Nothing,0)                                    :2_2:UnDeeper:
slAKA optional typically> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
slAKA optional typically> MATCH (EOK): <EMPTY>
slAKA optional typically> VALUE: ((Nothing,0),[])

****************** \ slAKA optional typically has returned (Nothing,0)                                    :2_2:UnDeeper:
****************** > |>>/base got Nothing                                                                 :2_2:UnDeeper:
|>>/base> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
|>>/base> MATCH (EOK): <EMPTY>
|>>/base> VALUE: ((Nothing,0),[])

***************** \ |>>/base has returned (Nothing,0)                                                      :2_2:UnDeeper:
***************** > slAKA: proceeding after base and entityalias are retrieved ...                         :2_2:UnDeeper:
***************** > pAKA: entityalias = Nothing                                                            :2_2:UnDeeper:
slAKA> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
slAKA> MATCH (COK): "top1"
slAKA> VALUE: ((("top1" :| [],Nothing),0),[])

**************** \ slAKA has returned (("top1" :| [],Nothing),0)                                            :2_2:UnDeeper:
**************** / undeepers                                                                                :2_2:UnDeeper:
***************** > sameLine/undeepers: reached end of line; now need to clear 0 UnDeepers                 :2_2:UnDeeper:
***************** > sameLine: success!                                                                     :2_2:UnDeeper:
undeepers> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
undeepers> MATCH (EOK): <EMPTY>
undeepers> VALUE: ((),[])

**************** \ undeepers has returned ()                                                                :2_2:UnDeeper:
pKeyValuesAka> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
pKeyValuesAka> MATCH (COK): "top1"
pKeyValuesAka> VALUE: (("top1" :| [],Nothing),[])

*************** \ pKeyValuesAka has returned ("top1" :| [],Nothing)                                          :2_2:UnDeeper:
pParamText(flat) first line: pKeyValues> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
pParamText(flat) first line: pKeyValues> MATCH (COK): "top1"
pParamText(flat) first line: pKeyValues> VALUE: (("top1" :| [],Nothing),[])

************** \ pParamText(flat) first line: pKeyValues has returned ("top1" :| [],Nothing)                  :2_2:UnDeeper:
************** / pParamText(flat) subsequent lines: sameMany pKeyValues                                       :2_2:UnDeeper:
*************** / manyIndentation/leaf?                                                                      :2_2:UnDeeper:
**************** / sameMany                                                                                 :2_2:UnDeeper:
***************** / pKeyValuesAka                                                                          :2_2:UnDeeper:
****************** / slAKA                                                                                :2_2:UnDeeper:
******************* / $*|                                                                                :2_2:UnDeeper:
******************** / slAKA base                                                                       :2_2:UnDeeper:
********************* / slKeyValues                                                                    :2_2:UnDeeper:
********************** / $*|                                                                          :2_2:UnDeeper:
*********************** / someSL                                                                     :2_2:UnDeeper:
************************ / pNumAsText                                                               :2_2:UnDeeper:
pNumAsText> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
pNumAsText> MATCH (EERR): <EMPTY>
pNumAsText> ERROR:
pNumAsText> offset=2:
pNumAsText> unexpected )
pNumAsText> expecting number

someSL> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
someSL> MATCH (EERR): <EMPTY>
someSL> ERROR:
someSL> offset=2:
someSL> unexpected )
someSL> expecting other text or number

$*|> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
$*|> MATCH (EERR): <EMPTY>
$*|> ERROR:
$*|> offset=2:
$*|> unexpected )
$*|> expecting other text or number

slKeyValues> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
slKeyValues> MATCH (EERR): <EMPTY>
slKeyValues> ERROR:
slKeyValues> offset=2:
slKeyValues> unexpected )
slKeyValues> expecting other text or number

slAKA base> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
slAKA base> MATCH (EERR): <EMPTY>
slAKA base> ERROR:
slAKA base> offset=2:
slAKA base> unexpected )
slAKA base> expecting other text or number

$*|> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
$*|> MATCH (EERR): <EMPTY>
$*|> ERROR:
$*|> offset=2:
$*|> unexpected )
$*|> expecting other text or number

slAKA> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
slAKA> MATCH (EERR): <EMPTY>
slAKA> ERROR:
slAKA> offset=2:
slAKA> unexpected )
slAKA> expecting other text or number

pKeyValuesAka> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
pKeyValuesAka> MATCH (EERR): <EMPTY>
pKeyValuesAka> ERROR:
pKeyValuesAka> offset=2:
pKeyValuesAka> unexpected )
pKeyValuesAka> expecting other text or number

sameMany> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
sameMany> MATCH (EOK): <EMPTY>
sameMany> VALUE: ([],[])

**************** \ sameMany has returned []                                                                 :2_2:UnDeeper:
manyIndentation/leaf?> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
manyIndentation/leaf?> MATCH (EOK): <EMPTY>
manyIndentation/leaf?> VALUE: ([],[])

*************** \ manyIndentation/leaf? has returned []                                                      :2_2:UnDeeper:
pParamText(flat) subsequent lines: sameMany pKeyValues> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
pParamText(flat) subsequent lines: sameMany pKeyValues> MATCH (EOK): <EMPTY>
pParamText(flat) subsequent lines: sameMany pKeyValues> VALUE: ([],[])

************** \ pParamText(flat) subsequent lines: sameMany pKeyValues has returned []                       :2_2:UnDeeper:
pParamText> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
pParamText> MATCH (COK): "top1"
pParamText> VALUE: (("top1" :| [],Nothing) :| [],[])

************* \ pParamText has returned ("top1" :| [],Nothing) :| []                                           :2_2:UnDeeper:
term p/3:plain p> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
term p/3:plain p> MATCH (COK): "top1"
term p/3:plain p> VALUE: (MyLeaf (("top1" :| [],Nothing) :| []),[])

************ \ term p/3:plain p has returned MyLeaf (("top1" :| [],Nothing) :| [])                              :2_2:UnDeeper:
term p/notLabelTerm> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
term p/notLabelTerm> MATCH (COK): "top1"
term p/notLabelTerm> VALUE: (MyLeaf (("top1" :| [],Nothing) :| []),[])

*********** \ term p/notLabelTerm has returned MyLeaf (("top1" :| [],Nothing) :| [])                             :2_2:UnDeeper:
term p> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
term p> MATCH (COK): "top1"
term p> VALUE: (MyLeaf (("top1" :| [],Nothing) :| []),[])

********** \ term p has returned MyLeaf (("top1" :| [],Nothing) :| [])                                            :2_2:UnDeeper:
********** / binary(Or)                                                                                           :2_2:UnDeeper:
binary(Or)> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
binary(Or)> MATCH (EERR): <EMPTY>
binary(Or)> ERROR:
binary(Or)> offset=2:
binary(Or)> unexpected )
binary(Or)> expecting OR

********** / binary(And)                                                                                          :2_2:UnDeeper:
binary(And)> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
binary(And)> MATCH (EERR): <EMPTY>
binary(And)> ERROR:
binary(And)> offset=2:
binary(And)> unexpected )
binary(And)> expecting AND

********** / binary(SetLess)                                                                                      :2_2:UnDeeper:
binary(SetLess)> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
binary(SetLess)> MATCH (EERR): <EMPTY>
binary(SetLess)> ERROR:
binary(SetLess)> offset=2:
binary(SetLess)> unexpected )
binary(SetLess)> expecting LESS

********** / binary(SetPlus)                                                                                      :2_2:UnDeeper:
binary(SetPlus)> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
binary(SetPlus)> MATCH (EERR): <EMPTY>
binary(SetPlus)> ERROR:
binary(SetPlus)> offset=2:
binary(SetPlus)> unexpected )
binary(SetPlus)> expecting PLUS

expression> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
expression> MATCH (COK): "top1"
expression> VALUE: (MyLeaf (("top1" :| [],Nothing) :| []),[])

********* \ expression has returned MyLeaf (("top1" :| [],Nothing) :| [])                                          :2_2:UnDeeper:
manyIndentation/leaf?> IN: "top1" ) OR ( "top2" ) OR ( "this is a l <…>
manyIndentation/leaf?> MATCH (COK): "top1"
manyIndentation/leaf?> VALUE: (MyLeaf (("top1" :| [],Nothing) :| []),[])

******** \ manyIndentation/leaf? has returned MyLeaf (("top1" :| [],Nothing) :| [])                                 :2_2:UnDeeper:
******** / myindented: consuming UnDeeper                                                                           :2_2:UnDeeper:
myindented: consuming UnDeeper> IN: ) OR ( "top2" ) OR ( "this is a label" E <…>
myindented: consuming UnDeeper> MATCH (COK): )
myindented: consuming UnDeeper> VALUE: (UnDeeper,[])

******** \ myindented: consuming UnDeeper has returned UnDeeper                                                  :2_1:Or:
someIndentation> IN: ( "top1" ) OR ( "top2" ) OR ( "this is a <…>
someIndentation> MATCH (COK): ( "top1" )
someIndentation> VALUE: (MyLeaf (("top1" :| [],Nothing) :| []),[])

******* \ someIndentation has returned MyLeaf (("top1" :| [],Nothing) :| [])                                      :2_1:Or:
term p/2:someIndentation expr p> IN: ( "top1" ) OR ( "top2" ) OR ( "this is a <…>
term p/2:someIndentation expr p> MATCH (COK): ( "top1" )
term p/2:someIndentation expr p> VALUE: (MyLeaf (("top1" :| [],Nothing) :| []),[])

****** \ term p/2:someIndentation expr p has returned MyLeaf (("top1" :| [],Nothing) :| [])                        :2_1:Or:
term p/notLabelTerm> IN: ( "top1" ) OR ( "top2" ) OR ( "this is a <…>
term p/notLabelTerm> MATCH (COK): ( "top1" )
term p/notLabelTerm> VALUE: (MyLeaf (("top1" :| [],Nothing) :| []),[])

***** \ term p/notLabelTerm has returned MyLeaf (("top1" :| [],Nothing) :| [])                                      :2_1:Or:
term p> IN: ( "top1" ) OR ( "top2" ) OR ( "this is a <…>
term p> MATCH (COK): ( "top1" )
term p> VALUE: (MyLeaf (("top1" :| [],Nothing) :| []),[])

**** \ term p has returned MyLeaf (("top1" :| [],Nothing) :| [])                                                     :2_1:Or:
**** / binary(Or)                                                                                                    :2_1:Or:
binary(Or)> IN: OR ( "top2" ) OR ( "this is a label" EOL <…>
binary(Or)> MATCH (COK): OR
binary(Or)> VALUE: (Or,[])

**** \ binary(Or) has returned Or                                                                                     :2_2:GoDeeper:
**** / term p                                                                                                         :2_2:GoDeeper:
***** / term p/notLabelTerm                                                                                          :2_2:GoDeeper:
****** / term p/2:someIndentation expr p                                                                            :2_2:GoDeeper:
******* / someIndentation                                                                                          :2_2:GoDeeper:
******** / myindented: consuming GoDeeper                                                                         :2_2:GoDeeper:
myindented: consuming GoDeeper> IN: ( "top2" ) OR ( "this is a label" EOL (  <…>
myindented: consuming GoDeeper> MATCH (COK): (
myindented: consuming GoDeeper> VALUE: (GoDeeper,[])

******** \ myindented: consuming GoDeeper has returned GoDeeper                                                    :2_2:Other "top2:
******** / manyIndentation/leaf?                                                                                   :2_2:Other "top2:
********* / expression                                                                                            :2_2:Other "top2:
********** / labelPrefix                                                                                         :2_2:Other "top2:
labelPrefix> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
labelPrefix> MATCH (EERR): <EMPTY>
labelPrefix> ERROR:
labelPrefix> offset=6:
labelPrefix> unexpected )

********** / term p                                                                                              :2_2:Other "top2:
*********** / term p/notLabelTerm                                                                               :2_2:Other "top2:
************ / term p/2:someIndentation expr p                                                                 :2_2:Other "top2:
************* / someIndentation                                                                               :2_2:Other "top2:
************** / myindented: consuming GoDeeper                                                              :2_2:Other "top2:
myindented: consuming GoDeeper> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
myindented: consuming GoDeeper> MATCH (EERR): <EMPTY>
myindented: consuming GoDeeper> ERROR:
myindented: consuming GoDeeper> offset=5:
myindented: consuming GoDeeper> unexpected "top2"
myindented: consuming GoDeeper> expecting (

someIndentation> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
someIndentation> MATCH (EERR): <EMPTY>
someIndentation> ERROR:
someIndentation> offset=5:
someIndentation> unexpected "top2"
someIndentation> expecting (

term p/2:someIndentation expr p> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
term p/2:someIndentation expr p> MATCH (EERR): <EMPTY>
term p/2:someIndentation expr p> ERROR:
term p/2:someIndentation expr p> offset=5:
term p/2:someIndentation expr p> unexpected "top2"
term p/2:someIndentation expr p> expecting (

************ / term p/3:plain p                                                                                :2_2:Other "top2:
************* / pParamText                                                                                    :2_2:Other "top2:
************** / pParamText(flat) first line: pKeyValues                                                     :2_2:Other "top2:
*************** / pKeyValuesAka                                                                             :2_2:Other "top2:
**************** / slAKA                                                                                   :2_2:Other "top2:
***************** / $*|                                                                                   :2_2:Other "top2:
****************** / slAKA base                                                                          :2_2:Other "top2:
******************* / slKeyValues                                                                       :2_2:Other "top2:
******************** / $*|                                                                             :2_2:Other "top2:
********************* / someSL                                                                        :2_2:Other "top2:
someSL> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
someSL> MATCH (COK): "top2"
someSL> VALUE: ((["top2"],0),[])

********************* \ someSL has returned (["top2"],0)                                               :3_2:UnDeeper:
$*|> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
$*|> MATCH (COK): "top2"
$*|> VALUE: ((["top2"],0),[])

******************** \ $*| has returned (["top2"],0)                                                    :3_2:UnDeeper:
******************** / |>>/recurse                                                                      :3_2:UnDeeper:
|>>/recurse> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=6:
|>>/recurse> unexpected )
|>>/recurse> expecting (

******************** / |>>/base                                                                         :3_2:UnDeeper:
********************* / |?| optional something                                                         :3_2:UnDeeper:
********************** / |>>/recurse                                                                  :3_2:UnDeeper:
|>>/recurse> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=6:
|>>/recurse> unexpected )
|>>/recurse> expecting (

********************** / |>>/base                                                                     :3_2:UnDeeper:
*********************** / slTypeSig                                                                  :3_2:UnDeeper:
************************ / $>|                                                                      :3_2:UnDeeper:
$>|> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
$>|> MATCH (EERR): <EMPTY>
$>|> ERROR:
$>|> offset=6:
$>|> unexpected )
$>|> expecting :: or IS

slTypeSig> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
slTypeSig> MATCH (EERR): <EMPTY>
slTypeSig> ERROR:
slTypeSig> offset=6:
slTypeSig> unexpected )
slTypeSig> expecting :: or IS

|>>/base> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/base> MATCH (EERR): <EMPTY>
|>>/base> ERROR:
|>>/base> offset=6:
|>>/base> unexpected )
|>>/base> expecting :: or IS

|?| optional something> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|?| optional something> MATCH (EOK): <EMPTY>
|?| optional something> VALUE: ((Nothing,0),[])

********************* \ |?| optional something has returned (Nothing,0)                                :3_2:UnDeeper:
********************* > |>>/base got Nothing                                                           :3_2:UnDeeper:
|>>/base> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/base> MATCH (EOK): <EMPTY>
|>>/base> VALUE: ((Nothing,0),[])

******************** \ |>>/base has returned (Nothing,0)                                                :3_2:UnDeeper:
slKeyValues> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
slKeyValues> MATCH (COK): "top2"
slKeyValues> VALUE: ((("top2" :| [],Nothing),0),[])

******************* \ slKeyValues has returned (("top2" :| [],Nothing),0)                                :3_2:UnDeeper:
slAKA base> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
slAKA base> MATCH (COK): "top2"
slAKA base> VALUE: ((("top2" :| [],Nothing),0),[])

****************** \ slAKA base has returned (("top2" :| [],Nothing),0)                                   :3_2:UnDeeper:
$*|> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
$*|> MATCH (COK): "top2"
$*|> VALUE: ((("top2" :| [],Nothing),0),[])

***************** \ $*| has returned (("top2" :| [],Nothing),0)                                            :3_2:UnDeeper:
***************** / |>>/recurse                                                                            :3_2:UnDeeper:
|>>/recurse> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=6:
|>>/recurse> unexpected )
|>>/recurse> expecting (

***************** / |>>/base                                                                               :3_2:UnDeeper:
****************** / slAKA optional akapart                                                               :3_2:UnDeeper:
******************* / |?| optional something                                                             :3_2:UnDeeper:
******************** / |>>/recurse                                                                      :3_2:UnDeeper:
|>>/recurse> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=6:
|>>/recurse> unexpected )
|>>/recurse> expecting (

******************** / |>>/base                                                                         :3_2:UnDeeper:
********************* / PAKA/akapart                                                                   :3_2:UnDeeper:
********************** / $>|                                                                          :3_2:UnDeeper:
*********************** / Aka Token                                                                  :3_2:UnDeeper:
Aka Token> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
Aka Token> MATCH (EERR): <EMPTY>
Aka Token> ERROR:
Aka Token> offset=6:
Aka Token> unexpected )
Aka Token> expecting AKA

$>|> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
$>|> MATCH (EERR): <EMPTY>
$>|> ERROR:
$>|> offset=6:
$>|> unexpected )
$>|> expecting AKA

PAKA/akapart> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
PAKA/akapart> MATCH (EERR): <EMPTY>
PAKA/akapart> ERROR:
PAKA/akapart> offset=6:
PAKA/akapart> unexpected )
PAKA/akapart> expecting AKA

|>>/base> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/base> MATCH (EERR): <EMPTY>
|>>/base> ERROR:
|>>/base> offset=6:
|>>/base> unexpected )
|>>/base> expecting AKA

|?| optional something> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|?| optional something> MATCH (EOK): <EMPTY>
|?| optional something> VALUE: ((Nothing,0),[])

******************* \ |?| optional something has returned (Nothing,0)                                    :3_2:UnDeeper:
slAKA optional akapart> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
slAKA optional akapart> MATCH (EOK): <EMPTY>
slAKA optional akapart> VALUE: ((Nothing,0),[])

****************** \ slAKA optional akapart has returned (Nothing,0)                                      :3_2:UnDeeper:
****************** > |>>/base got Nothing                                                                 :3_2:UnDeeper:
|>>/base> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/base> MATCH (EOK): <EMPTY>
|>>/base> VALUE: ((Nothing,0),[])

***************** \ |>>/base has returned (Nothing,0)                                                      :3_2:UnDeeper:
***************** / |>>/recurse                                                                            :3_2:UnDeeper:
|>>/recurse> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=6:
|>>/recurse> unexpected )
|>>/recurse> expecting (

***************** / |>>/base                                                                               :3_2:UnDeeper:
****************** / slAKA optional typically                                                             :3_2:UnDeeper:
******************* / |?| optional something                                                             :3_2:UnDeeper:
******************** / |>>/recurse                                                                      :3_2:UnDeeper:
|>>/recurse> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/recurse> MATCH (EERR): <EMPTY>
|>>/recurse> ERROR:
|>>/recurse> offset=6:
|>>/recurse> unexpected )
|>>/recurse> expecting (

******************** / |>>/base                                                                         :3_2:UnDeeper:
********************* / typically                                                                      :3_2:UnDeeper:
********************** / $>|                                                                          :3_2:UnDeeper:
$>|> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
$>|> MATCH (EERR): <EMPTY>
$>|> ERROR:
$>|> offset=6:
$>|> unexpected )
$>|> expecting TYPICALLY

typically> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
typically> MATCH (EERR): <EMPTY>
typically> ERROR:
typically> offset=6:
typically> unexpected )
typically> expecting TYPICALLY

|>>/base> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/base> MATCH (EERR): <EMPTY>
|>>/base> ERROR:
|>>/base> offset=6:
|>>/base> unexpected )
|>>/base> expecting TYPICALLY

|?| optional something> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|?| optional something> MATCH (EOK): <EMPTY>
|?| optional something> VALUE: ((Nothing,0),[])

******************* \ |?| optional something has returned (Nothing,0)                                    :3_2:UnDeeper:
slAKA optional typically> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
slAKA optional typically> MATCH (EOK): <EMPTY>
slAKA optional typically> VALUE: ((Nothing,0),[])

****************** \ slAKA optional typically has returned (Nothing,0)                                    :3_2:UnDeeper:
****************** > |>>/base got Nothing                                                                 :3_2:UnDeeper:
|>>/base> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
|>>/base> MATCH (EOK): <EMPTY>
|>>/base> VALUE: ((Nothing,0),[])

***************** \ |>>/base has returned (Nothing,0)                                                      :3_2:UnDeeper:
***************** > slAKA: proceeding after base and entityalias are retrieved ...                         :3_2:UnDeeper:
***************** > pAKA: entityalias = Nothing                                                            :3_2:UnDeeper:
slAKA> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
slAKA> MATCH (COK): "top2"
slAKA> VALUE: ((("top2" :| [],Nothing),0),[])

**************** \ slAKA has returned (("top2" :| [],Nothing),0)                                            :3_2:UnDeeper:
**************** / undeepers                                                                                :3_2:UnDeeper:
***************** > sameLine/undeepers: reached end of line; now need to clear 0 UnDeepers                 :3_2:UnDeeper:
***************** > sameLine: success!                                                                     :3_2:UnDeeper:
undeepers> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
undeepers> MATCH (EOK): <EMPTY>
undeepers> VALUE: ((),[])

**************** \ undeepers has returned ()                                                                :3_2:UnDeeper:
pKeyValuesAka> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
pKeyValuesAka> MATCH (COK): "top2"
pKeyValuesAka> VALUE: (("top2" :| [],Nothing),[])

*************** \ pKeyValuesAka has returned ("top2" :| [],Nothing)                                          :3_2:UnDeeper:
pParamText(flat) first line: pKeyValues> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
pParamText(flat) first line: pKeyValues> MATCH (COK): "top2"
pParamText(flat) first line: pKeyValues> VALUE: (("top2" :| [],Nothing),[])

************** \ pParamText(flat) first line: pKeyValues has returned ("top2" :| [],Nothing)                  :3_2:UnDeeper:
************** / pParamText(flat) subsequent lines: sameMany pKeyValues                                       :3_2:UnDeeper:
*************** / manyIndentation/leaf?                                                                      :3_2:UnDeeper:
**************** / sameMany                                                                                 :3_2:UnDeeper:
***************** / pKeyValuesAka                                                                          :3_2:UnDeeper:
****************** / slAKA                                                                                :3_2:UnDeeper:
******************* / $*|                                                                                :3_2:UnDeeper:
******************** / slAKA base                                                                       :3_2:UnDeeper:
********************* / slKeyValues                                                                    :3_2:UnDeeper:
********************** / $*|                                                                          :3_2:UnDeeper:
*********************** / someSL                                                                     :3_2:UnDeeper:
************************ / pNumAsText                                                               :3_2:UnDeeper:
pNumAsText> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
pNumAsText> MATCH (EERR): <EMPTY>
pNumAsText> ERROR:
pNumAsText> offset=6:
pNumAsText> unexpected )
pNumAsText> expecting number

someSL> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
someSL> MATCH (EERR): <EMPTY>
someSL> ERROR:
someSL> offset=6:
someSL> unexpected )
someSL> expecting other text or number

$*|> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
$*|> MATCH (EERR): <EMPTY>
$*|> ERROR:
$*|> offset=6:
$*|> unexpected )
$*|> expecting other text or number

slKeyValues> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
slKeyValues> MATCH (EERR): <EMPTY>
slKeyValues> ERROR:
slKeyValues> offset=6:
slKeyValues> unexpected )
slKeyValues> expecting other text or number

slAKA base> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
slAKA base> MATCH (EERR): <EMPTY>
slAKA base> ERROR:
slAKA base> offset=6:
slAKA base> unexpected )
slAKA base> expecting other text or number

$*|> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
$*|> MATCH (EERR): <EMPTY>
$*|> ERROR:
$*|> offset=6:
$*|> unexpected )
$*|> expecting other text or number

slAKA> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
slAKA> MATCH (EERR): <EMPTY>
slAKA> ERROR:
slAKA> offset=6:
slAKA> unexpected )
slAKA> expecting other text or number

pKeyValuesAka> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
pKeyValuesAka> MATCH (EERR): <EMPTY>
pKeyValuesAka> ERROR:
pKeyValuesAka> offset=6:
pKeyValuesAka> unexpected )
pKeyValuesAka> expecting other text or number

sameMany> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
sameMany> MATCH (EOK): <EMPTY>
sameMany> VALUE: ([],[])

**************** \ sameMany has returned []                                                                 :3_2:UnDeeper:
manyIndentation/leaf?> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
manyIndentation/leaf?> MATCH (EOK): <EMPTY>
manyIndentation/leaf?> VALUE: ([],[])

*************** \ manyIndentation/leaf? has returned []                                                      :3_2:UnDeeper:
pParamText(flat) subsequent lines: sameMany pKeyValues> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
pParamText(flat) subsequent lines: sameMany pKeyValues> MATCH (EOK): <EMPTY>
pParamText(flat) subsequent lines: sameMany pKeyValues> VALUE: ([],[])

************** \ pParamText(flat) subsequent lines: sameMany pKeyValues has returned []                       :3_2:UnDeeper:
pParamText> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
pParamText> MATCH (COK): "top2"
pParamText> VALUE: (("top2" :| [],Nothing) :| [],[])

************* \ pParamText has returned ("top2" :| [],Nothing) :| []                                           :3_2:UnDeeper:
term p/3:plain p> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
term p/3:plain p> MATCH (COK): "top2"
term p/3:plain p> VALUE: (MyLeaf (("top2" :| [],Nothing) :| []),[])

************ \ term p/3:plain p has returned MyLeaf (("top2" :| [],Nothing) :| [])                              :3_2:UnDeeper:
term p/notLabelTerm> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
term p/notLabelTerm> MATCH (COK): "top2"
term p/notLabelTerm> VALUE: (MyLeaf (("top2" :| [],Nothing) :| []),[])

*********** \ term p/notLabelTerm has returned MyLeaf (("top2" :| [],Nothing) :| [])                             :3_2:UnDeeper:
term p> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
term p> MATCH (COK): "top2"
term p> VALUE: (MyLeaf (("top2" :| [],Nothing) :| []),[])

********** \ term p has returned MyLeaf (("top2" :| [],Nothing) :| [])                                            :3_2:UnDeeper:
********** / binary(Or)                                                                                           :3_2:UnDeeper:
binary(Or)> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
binary(Or)> MATCH (EERR): <EMPTY>
binary(Or)> ERROR:
binary(Or)> offset=6:
binary(Or)> unexpected )
binary(Or)> expecting OR

********** / binary(And)                                                                                          :3_2:UnDeeper:
binary(And)> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
binary(And)> MATCH (EERR): <EMPTY>
binary(And)> ERROR:
binary(And)> offset=6:
binary(And)> unexpected )
binary(And)> expecting AND

********** / binary(SetLess)                                                                                      :3_2:UnDeeper:
binary(SetLess)> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
binary(SetLess)> MATCH (EERR): <EMPTY>
binary(SetLess)> ERROR:
binary(SetLess)> offset=6:
binary(SetLess)> unexpected )
binary(SetLess)> expecting LESS

********** / binary(SetPlus)                                                                                      :3_2:UnDeeper:
binary(SetPlus)> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
binary(SetPlus)> MATCH (EERR): <EMPTY>
binary(SetPlus)> ERROR:
binary(SetPlus)> offset=6:
binary(SetPlus)> unexpected )
binary(SetPlus)> expecting PLUS

expression> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
expression> MATCH (COK): "top2"
expression> VALUE: (MyLeaf (("top2" :| [],Nothing) :| []),[])

********* \ expression has returned MyLeaf (("top2" :| [],Nothing) :| [])                                          :3_2:UnDeeper:
manyIndentation/leaf?> IN: "top2" ) OR ( "this is a label" EOL ( "m <…>
manyIndentation/leaf?> MATCH (COK): "top2"
manyIndentation/leaf?> VALUE: (MyLeaf (("top2" :| [],Nothing) :| []),[])

******** \ manyIndentation/leaf? has returned MyLeaf (("top2" :| [],Nothing) :| [])                                 :3_2:UnDeeper:
******** / myindented: consuming UnDeeper                                                                           :3_2:UnDeeper:
myindented: consuming UnDeeper> IN: ) OR ( "this is a label" EOL ( "mid3" )  <…>
myindented: consuming UnDeeper> MATCH (COK): )
myindented: consuming UnDeeper> VALUE: (UnDeeper,[])

******** \ myindented: consuming UnDeeper has returned UnDeeper                                                  :3_1:Or:
someIndentation> IN: ( "top2" ) OR ( "this is a label" EOL (  <…>
someIndentation> MATCH (COK): ( "top2" )
someIndentation> VALUE: (MyLeaf (("top2" :| [],Nothing) :| []),[])

******* \ someIndentation has returned MyLeaf (("top2" :| [],Nothing) :| [])                                      :3_1:Or:
term p/2:someIndentation expr p> IN: ( "top2" ) OR ( "this is a label" EOL (  <…>
term p/2:someIndentation expr p> MATCH (COK): ( "top2" )
term p/2:someIndentation expr p> VALUE: (MyLeaf (("top2" :| [],Nothing) :| []),[])

****** \ term p/2:someIndentation expr p has returned MyLeaf (("top2" :| [],Nothing) :| [])                        :3_1:Or:
term p/notLabelTerm> IN: ( "top2" ) OR ( "this is a label" EOL (  <…>
term p/notLabelTerm> MATCH (COK): ( "top2" )
term p/notLabelTerm> VALUE: (MyLeaf (("top2" :| [],Nothing) :| []),[])

***** \ term p/notLabelTerm has returned MyLeaf (("top2" :| [],Nothing) :| [])                                      :3_1:Or:
term p> IN: ( "top2" ) OR ( "this is a label" EOL (  <…>
term p> MATCH (COK): ( "top2" )
term p> VALUE: (MyLeaf (("top2" :| [],Nothing) :| []),[])

**** \ term p has returned MyLeaf (("top2" :| [],Nothing) :| [])                                                     :3_1:Or:
**** / binary(Or)                                                                                                    :3_1:Or:
binary(Or)> IN: OR ( "this is a label" EOL ( "mid3" ) OR <…>
binary(Or)> MATCH (COK): OR
binary(Or)> VALUE: (Or,[])

**** \ binary(Or) has returned Or                                                                                     :3_2:GoDeeper:
**** / term p                                                                                                         :3_2:GoDeeper:
***** / term p/notLabelTerm                                                                                          :3_2:GoDeeper:
****** / term p/2:someIndentation expr p                                                                            :3_2:GoDeeper:
******* / someIndentation                                                                                          :3_2:GoDeeper:
******** / myindented: consuming GoDeeper                                                                         :3_2:GoDeeper:
myindented: consuming GoDeeper> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
myindented: consuming GoDeeper> MATCH (COK): (
myindented: consuming GoDeeper> VALUE: (GoDeeper,[])

******** \ myindented: consuming GoDeeper has returned GoDeeper                                                    :3_2:Other "this:
******** / manyIndentation/leaf?                                                                                   :3_2:Other "this:
********* / expression                                                                                            :3_2:Other "this:
********** / labelPrefix                                                                                         :3_2:Other "this:
labelPrefix> IN: "this is a label" EOL ( "mid3" ) OR ( "m <…>
labelPrefix> MATCH (COK): "this is a label"
labelPrefix> VALUE: ("this is a label",[])

********** \ labelPrefix has returned "this is a label"                                                          :3_2:EOL:
********** / term p                                                                                              :3_2:EOL:
*********** / term p/notLabelTerm                                                                               :3_2:EOL:
************ / term p/2:someIndentation expr p                                                                 :3_2:EOL:
************* / someIndentation                                                                               :3_2:EOL:
************** / myindented: consuming GoDeeper                                                              :3_2:EOL:
myindented: consuming GoDeeper> IN: EOL ( "mid3" ) OR ( "mid4" ) )
myindented: consuming GoDeeper> MATCH (EERR): <EMPTY>
myindented: consuming GoDeeper> ERROR:
myindented: consuming GoDeeper> offset=10:
myindented: consuming GoDeeper> unexpected EOL
myindented: consuming GoDeeper> expecting (

someIndentation> IN: EOL ( "mid3" ) OR ( "mid4" ) )
someIndentation> MATCH (EERR): <EMPTY>
someIndentation> ERROR:
someIndentation> offset=10:
someIndentation> unexpected EOL
someIndentation> expecting (

term p/2:someIndentation expr p> IN: EOL ( "mid3" ) OR ( "mid4" ) )
term p/2:someIndentation expr p> MATCH (EERR): <EMPTY>
term p/2:someIndentation expr p> ERROR:
term p/2:someIndentation expr p> offset=10:
term p/2:someIndentation expr p> unexpected EOL
term p/2:someIndentation expr p> expecting (

************ / term p/3:plain p                                                                                :3_2:EOL:
************* / pParamText                                                                                    :3_2:EOL:
************** / pParamText(flat) first line: pKeyValues                                                     :3_2:EOL:
*************** / pKeyValuesAka                                                                             :3_2:EOL:
**************** / slAKA                                                                                   :3_2:EOL:
***************** / $*|                                                                                   :3_2:EOL:
****************** / slAKA base                                                                          :3_2:EOL:
******************* / slKeyValues                                                                       :3_2:EOL:
******************** / $*|                                                                             :3_2:EOL:
********************* / someSL                                                                        :3_2:EOL:
********************** / pNumAsText                                                                  :3_2:EOL:
pNumAsText> IN: EOL ( "mid3" ) OR ( "mid4" ) )
pNumAsText> MATCH (EERR): <EMPTY>
pNumAsText> ERROR:
pNumAsText> offset=10:
pNumAsText> unexpected EOL
pNumAsText> expecting number

someSL> IN: EOL ( "mid3" ) OR ( "mid4" ) )
someSL> MATCH (EERR): <EMPTY>
someSL> ERROR:
someSL> offset=10:
someSL> unexpected EOL
someSL> expecting other text or number

$*|> IN: EOL ( "mid3" ) OR ( "mid4" ) )
$*|> MATCH (EERR): <EMPTY>
$*|> ERROR:
$*|> offset=10:
$*|> unexpected EOL
$*|> expecting other text or number

slKeyValues> IN: EOL ( "mid3" ) OR ( "mid4" ) )
slKeyValues> MATCH (EERR): <EMPTY>
slKeyValues> ERROR:
slKeyValues> offset=10:
slKeyValues> unexpected EOL
slKeyValues> expecting other text or number

slAKA base> IN: EOL ( "mid3" ) OR ( "mid4" ) )
slAKA base> MATCH (EERR): <EMPTY>
slAKA base> ERROR:
slAKA base> offset=10:
slAKA base> unexpected EOL
slAKA base> expecting other text or number

$*|> IN: EOL ( "mid3" ) OR ( "mid4" ) )
$*|> MATCH (EERR): <EMPTY>
$*|> ERROR:
$*|> offset=10:
$*|> unexpected EOL
$*|> expecting other text or number

slAKA> IN: EOL ( "mid3" ) OR ( "mid4" ) )
slAKA> MATCH (EERR): <EMPTY>
slAKA> ERROR:
slAKA> offset=10:
slAKA> unexpected EOL
slAKA> expecting other text or number

pKeyValuesAka> IN: EOL ( "mid3" ) OR ( "mid4" ) )
pKeyValuesAka> MATCH (EERR): <EMPTY>
pKeyValuesAka> ERROR:
pKeyValuesAka> offset=10:
pKeyValuesAka> unexpected EOL
pKeyValuesAka> expecting other text or number

pParamText(flat) first line: pKeyValues> IN: EOL ( "mid3" ) OR ( "mid4" ) )
pParamText(flat) first line: pKeyValues> MATCH (EERR): <EMPTY>
pParamText(flat) first line: pKeyValues> ERROR:
pParamText(flat) first line: pKeyValues> offset=10:
pParamText(flat) first line: pKeyValues> unexpected EOL
pParamText(flat) first line: pKeyValues> expecting other text or number

pParamText> IN: EOL ( "mid3" ) OR ( "mid4" ) )
pParamText> MATCH (EERR): <EMPTY>
pParamText> ERROR:
pParamText> offset=10:
pParamText> unexpected EOL
pParamText> expecting other text or number

term p/3:plain p> IN: EOL ( "mid3" ) OR ( "mid4" ) )
term p/3:plain p> MATCH (EERR): <EMPTY>
term p/3:plain p> ERROR:
term p/3:plain p> offset=10:
term p/3:plain p> unexpected EOL
term p/3:plain p> expecting other text or number

term p/notLabelTerm> IN: EOL ( "mid3" ) OR ( "mid4" ) )
term p/notLabelTerm> MATCH (EERR): <EMPTY>
term p/notLabelTerm> ERROR:
term p/notLabelTerm> offset=10:
term p/notLabelTerm> unexpected EOL
term p/notLabelTerm> expecting ( or term

term p> IN: EOL ( "mid3" ) OR ( "mid4" ) )
term p> MATCH (EERR): <EMPTY>
term p> ERROR:
term p> offset=10:
term p> unexpected EOL
term p> expecting ( or term

expression> IN: "this is a label" EOL ( "mid3" ) OR ( "m <…>
expression> MATCH (CERR): "this is a label"
expression> ERROR:
expression> offset=10:
expression> unexpected EOL
expression> expecting (, NOT, or term

manyIndentation/leaf?> IN: "this is a label" EOL ( "mid3" ) OR ( "m <…>
manyIndentation/leaf?> MATCH (EERR): <EMPTY>
manyIndentation/leaf?> ERROR:
manyIndentation/leaf?> offset=10:
manyIndentation/leaf?> unexpected EOL
manyIndentation/leaf?> expecting (, NOT, or term

******** / manyIndentation/deeper; calling someIndentation                                                         :3_2:Other "this:
********* / someIndentation                                                                                       :3_2:Other "this:
********** / myindented: consuming GoDeeper                                                                      :3_2:Other "this:
myindented: consuming GoDeeper> IN: "this is a label" EOL ( "mid3" ) OR ( "m <…>
myindented: consuming GoDeeper> MATCH (EERR): <EMPTY>
myindented: consuming GoDeeper> ERROR:
myindented: consuming GoDeeper> offset=9:
myindented: consuming GoDeeper> unexpected "this is a label"
myindented: consuming GoDeeper> expecting (

someIndentation> IN: "this is a label" EOL ( "mid3" ) OR ( "m <…>
someIndentation> MATCH (EERR): <EMPTY>
someIndentation> ERROR:
someIndentation> offset=9:
someIndentation> unexpected "this is a label"
someIndentation> expecting (

manyIndentation/deeper; calling someIndentation> IN: "this is a label" EOL ( "mid3" ) OR ( "m <…>
manyIndentation/deeper; calling someIndentation> MATCH (EERR): <EMPTY>
manyIndentation/deeper; calling someIndentation> ERROR:
manyIndentation/deeper; calling someIndentation> offset=9:
manyIndentation/deeper; calling someIndentation> unexpected "this is a label"
manyIndentation/deeper; calling someIndentation> expecting (

someIndentation> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
someIndentation> MATCH (CERR): (
someIndentation> ERROR:
someIndentation> offset=10:
someIndentation> unexpected EOL
someIndentation> expecting (, NOT, or term

term p/2:someIndentation expr p> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
term p/2:someIndentation expr p> MATCH (CERR): (
term p/2:someIndentation expr p> ERROR:
term p/2:someIndentation expr p> offset=10:
term p/2:someIndentation expr p> unexpected EOL
term p/2:someIndentation expr p> expecting (, NOT, or term

****** / term p/3:plain p                                                                                           :3_2:GoDeeper:
******* / pParamText                                                                                               :3_2:GoDeeper:
******** / pParamText(flat) first line: pKeyValues                                                                :3_2:GoDeeper:
********* / pKeyValuesAka                                                                                        :3_2:GoDeeper:
********** / slAKA                                                                                              :3_2:GoDeeper:
*********** / $*|                                                                                              :3_2:GoDeeper:
************ / slAKA base                                                                                     :3_2:GoDeeper:
************* / slKeyValues                                                                                  :3_2:GoDeeper:
************** / $*|                                                                                        :3_2:GoDeeper:
*************** / someSL                                                                                   :3_2:GoDeeper:
**************** / pNumAsText                                                                             :3_2:GoDeeper:
pNumAsText> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
pNumAsText> MATCH (EERR): <EMPTY>
pNumAsText> ERROR:
pNumAsText> offset=8:
pNumAsText> unexpected (
pNumAsText> expecting number

someSL> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
someSL> MATCH (EERR): <EMPTY>
someSL> ERROR:
someSL> offset=8:
someSL> unexpected (
someSL> expecting other text or number

$*|> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
$*|> MATCH (EERR): <EMPTY>
$*|> ERROR:
$*|> offset=8:
$*|> unexpected (
$*|> expecting other text or number

slKeyValues> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
slKeyValues> MATCH (EERR): <EMPTY>
slKeyValues> ERROR:
slKeyValues> offset=8:
slKeyValues> unexpected (
slKeyValues> expecting other text or number

slAKA base> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
slAKA base> MATCH (EERR): <EMPTY>
slAKA base> ERROR:
slAKA base> offset=8:
slAKA base> unexpected (
slAKA base> expecting other text or number

$*|> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
$*|> MATCH (EERR): <EMPTY>
$*|> ERROR:
$*|> offset=8:
$*|> unexpected (
$*|> expecting other text or number

slAKA> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
slAKA> MATCH (EERR): <EMPTY>
slAKA> ERROR:
slAKA> offset=8:
slAKA> unexpected (
slAKA> expecting other text or number

pKeyValuesAka> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
pKeyValuesAka> MATCH (EERR): <EMPTY>
pKeyValuesAka> ERROR:
pKeyValuesAka> offset=8:
pKeyValuesAka> unexpected (
pKeyValuesAka> expecting other text or number

pParamText(flat) first line: pKeyValues> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
pParamText(flat) first line: pKeyValues> MATCH (EERR): <EMPTY>
pParamText(flat) first line: pKeyValues> ERROR:
pParamText(flat) first line: pKeyValues> offset=8:
pParamText(flat) first line: pKeyValues> unexpected (
pParamText(flat) first line: pKeyValues> expecting other text or number

pParamText> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
pParamText> MATCH (EERR): <EMPTY>
pParamText> ERROR:
pParamText> offset=8:
pParamText> unexpected (
pParamText> expecting other text or number

term p/3:plain p> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
term p/3:plain p> MATCH (EERR): <EMPTY>
term p/3:plain p> ERROR:
term p/3:plain p> offset=8:
term p/3:plain p> unexpected (
term p/3:plain p> expecting other text or number

term p/notLabelTerm> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
term p/notLabelTerm> MATCH (EERR): <EMPTY>
term p/notLabelTerm> ERROR:
term p/notLabelTerm> offset=10:
term p/notLabelTerm> unexpected EOL
term p/notLabelTerm> expecting (, NOT, or term

term p> IN: ( "this is a label" EOL ( "mid3" ) OR (  <…>
term p> MATCH (EERR): <EMPTY>
term p> ERROR:
term p> offset=10:
term p> unexpected EOL
term p> expecting (, NOT, or term

expression> IN: ( "top1" ) OR ( "top2" ) OR ( "this is a <…>
expression> MATCH (CERR): ( "top1" ) OR ( "top2" ) OR
expression> ERROR:
expression> offset=10:
expression> unexpected EOL
expression> expecting (, NOT, or term

expr pParamText> IN: ( "top1" ) OR ( "top2" ) OR ( "this is a <…>
expr pParamText> MATCH (CERR): ( "top1" ) OR ( "top2" ) OR
expr pParamText> ERROR:
expr pParamText> offset=10:
expr pParamText> unexpected EOL
expr pParamText> expecting (, NOT, or term


our new parser
  indent-2-c-3 FAILED [1]

Failures:

  test/Spec.hs:124:3: 
  1) our new parser indent-2-c-3
       expected: [(MyAny [MyLeaf (("top1" :| [],Nothing) :| []),MyLeaf (("top2" :| [],Nothing) :| []),MyLabel ["this is a label"] (MyAny [MyLeaf (("mid3" :| [],Nothing) :| []),MyLeaf (("mid4" :| [],Nothing) :| [])])],[])]
       but parsing failed with error:
       3:2:
       unexpected EOL
       expecting (, NOT, or term
                         top1                                                 
       OR                top2                                                 
       OR                ✳ this is a label                                    
                                           mid3                               
                         OR                mid4                               
       

  To rerun use: --match "/our new parser/indent-2-c-3/"

Randomized with seed 1397798348

Finished in 0.0089 seconds
1 example, 1 failure

natural4> Test suite natural4-test failed
Test suite failure for package natural4-0.1.0.0
    natural4-test:  exited with: ExitFailure 1
Logs printed to console

