name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          cabal-version: '3.6.2.0'

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('lib/haskell/**/package.yaml','lib/haskell/**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('lib/haskell/**/package.yaml','lib/haskell/**/stack.yaml.lock') }}
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('lib/haskell/**/package.yaml') }}
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Ubuntu Prerequisites (libpcre)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install libpcre3-dev
      - name: Install MacOS Prerequisites (libpcre)
        if: startsWith(matrix.os, 'macOS')
        run: |
          brew install pcre

      - name: Build explainable
        run: stack build
        working-directory: lib/haskell/explainable
      - name: Test explainable
        run: stack test
        working-directory: lib/haskell/explainable
      - name: Build anyall
        run: stack build
        working-directory: lib/haskell/anyall
      - name: Test anyall
        run: stack test
        working-directory: lib/haskell/anyall
      - name: Build natural4
        run: stack build
        working-directory: lib/haskell/natural4
      - name: Test natural4
        run: stack test
        working-directory: lib/haskell/natural4
